### ISSUE TITLE
Expose changes in API

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#101]
I originally tried to paper over the idea of “changes” in the API and keep things simple by just annotating versions. Over time, it’s become more and more obvious that this was a bad idea. We should expose actual change objects in the API. We even already have a reasonable route for this:

- `GET /api/v0/pages/{page_id}/changes` - list changes (ordered by `to_version`, then `from_version`)
- `GET /api/v0/pages/{page_id}/changes/{from_version_id}..{to_version_id}` - a single change

Should we should also remove `current_annotation` from `Version`? (Note it already exists on `Change` and I think we would keep it there). I’m feeling like using a version as a shortcut to the change between a version and its preceding version is causing more confusion than help, but would love feedback (would also remove the `GET|POST /api/v0/pages/{id}/versions/{id}/annotations` endpoints).

Note this might also implicitly solve #4, since you could just query for the list of changes because we only store changes when annotations have happened.

/cc @danielballan @lightandluck

**Comment by danielballan** [comment]
I agree those routes are sensible.

> Should we should also remove current_annotation from Version? 

You know I already agree with this one. :- ) @janakrajchadha brought this up in one of our conversations too.

**Comment by lightandluck** [comment]
Agree with all points. Exposing changes and removing the `current annotation` would make it explicitly clear what we are dealing with. I was really confused how things related until you recently explained it to me. This should avoid that confusion for future contributors.
