### ISSUE TITLE
Update changes’ priority attribute based on annotations

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#102]
We originally had the `priority` attribute on `Change` objects as a float between `0` and `1`, indicating the priority of the change for humans to evaluate. We also thought we’d set it by posting an annotation with a specially named field (probably `priority`, but we never really decided). We need to actually put this into practice.

However, now that a lot of time has passed, I think I’ve got some questions or confusion I’d appreciate feedback on:

1. Somewhere along the line this got kinda fuzzy for me and merged with the concept of “significance” in my head. (In fact, I just claimed to @lightandluck that we had a `significance` attribute, but was actually thinking of this `priority` attribute). Are these different concepts or no? Do we need a second `significance` attribute that works similarly or should we merge these two ideas? (Which name do we choose?)

2. I initially wrote this with a default of `0.5`. Annotating with a lower value would effectively deprioritize a change, while a higher value would prioritize. Not sure this was the right decision, especially in the case of “significance.” Should this have a `NULL` or `-1` or similar “unset” value for its default instead? Or just `0` (I feel like we need the ability deprioritize/mark-as-definitely-not-worth-looking-at, so I’m not a huge fan of `0`)?

3. What annotation property name should cause this field to update? (Or should we abandon that idea and just `POST /api/v0/pages/{id}/changes/{a}..{b}/priority`?)

4. Does a second change to the `priority` attribute replace the previous value or does it somehow combine/multiply? (I’m thinking replace, for simplicity’s sake.)

/cc @danielballan @lightandluck 

(Marking as priority because we need this or something related to store significance data in the DB as discussed this afternoon.)

**Comment by danielballan** [comment]
1. I think a Change has both a `priority` and a `significance`. The `priority` will be used for sorting Changes for the hypothetical analyst who only has time to review some of the Pages that they are tasked with. I think our filtering pipeline will seed each Change with an initial priority. (At first, it might be as simple as, "If the bytes are identical, `priority=0`; otherwise `priority=1`. It can grow smoothly for there.) The Change's `significance` is aggregate property of its annotations.

2. I like `NULL` for unset. (`-1` as a sentinel makes it easy to commit math errors.) I agree that we need `0` for "lowest priority" and "lowest significance".

3. A Change's `significance` could be a simple average of the "Is this Change significant?" field in the annotation (0=no, 1=yes). I think we should punt for now on the question of how annotations make `priority` update. It looks subtle to me. Each annotation should decrease the priority, unless the annotations _disagree_ in which case the priority should go up... but we're not yet at the point where multiple analysts are reviewing the same Change.

4. Agree -- replace for now.

**Comment by lightandluck** [comment]
Ok and agree with all of Dan's suggestions.

To confirm, if we do what Dan suggests, when marking something as an`important change`, UI should create an annotation with `priority=1`? Looks like I can ignore `significance` for v0?

**Comment by danielballan** [comment]
Actually I would keep that separation even in v0: important change in the UI should put something in the annotation that can be surfaced by a query on the changes.

**Comment by lightandluck** [comment]
Aww, makes sense for UI to have it's own. I forget that DB is slated for bigger things =)

How about UI uses:
`isImportantChange: 0 or 1`
`isDictionary: 0 or 1`

Just to keep in line with analyst terminology. 
@Mr0grog @danielballan

**Comment by Mr0grog** [comment]
Hmmm, I don’t think we ever want the UI to set priority (that’s more a tool for automated things to basically tell the UI what order to present things to the user in), but I was thinking “important change” and “significance” are about the same thing.

So I’m thinking UI would…

- post an annotation with `{significance: 1}` (or some other agreed upon value? `0.5`?) when checking/clicking “important change”
- post an annotation with `{isDictionary: true}` for dictionary stuff

**Comment by Mr0grog** [comment]
OK, I started some work over on #105. It’s just making `priority` nullable right now, but it seems like I at least need to also add `significance`. Are we still comfortable with its schema being the same as `priority`? That is:

- Name: `significance`
- Type: `float`
- Range: `0.0-1.0`
- Default: `NULL`

Then the next thing is to make DB update set those fields whenever an annotation with the same name is submitted. For now it’ll just replace the current value with the one from the annotation. Is that good?

Anything else I am missing that needs to happen on the DB side for now?

**Comment by lightandluck** [comment]
I think UI should post a 1st pass `important change` with a `{significance: 0.5}` The first pass isn't confirmed or double-checked yet, mainly just filtering for perspective "important changes". `1` can be reserved for the confirmed ones, ready for stand-alone reports, etc.

`{isDictionary: true}` works

> Are we still comfortable with its schema being the same as priority?
Yes

> ...replace the current value with the one from the annotation
Yes

> Anything else I am missing that needs to happen on the DB side for now?
If it's possible, while you're in the bowels of the beast, if you can create route that returns changes with `significance` > 0.5 (if we agree upon that threshold), it would be real easy to create an `important changes` list view. ;-) But that's just me being greedy, totally unnecessary at this time

**Comment by Mr0grog** [comment]
> while you're in the bowels of the beast, if you can create route that returns changes with significance >= 0.5

Definitely! It’ll be the same as the `priority` queries in #104, so you would do:

```
GET /api/v0/pages/{id}/changes?significance_gte=0.5
```

(Unless you think those parameters should work, differently, in which case, please comment on #104.)

**Comment by lightandluck** [comment]
Perfect! I'll take a look at #104 and add my review
