### ISSUE TITLE
Consider making query params case-insensitive?

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#120]
Just had a quick call with one of the analysts, who I was introducing to the API. He tried to query by URL but was getting results he shouldn’t have (Fish and Wildlife pages when searching for `blm.gov` pages). It turned out he used the param `URL=https://www.blm.gov/*` instead of `url=https://www.blm.gov/*`. Should we make these param names case-insensitive? (We definitely should not for the values, of course.)

**Comment by mhucka** [comment]
That seems like a good idea!

**Comment by lightandluck** [comment]
Seconded

**Comment by Mr0grog** [comment]
Doesn't look like there’s a great way to do this in Rails; the easiest approach may be to create a middleware that lower-cases all query parameters.
