### ISSUE TITLE
Add endpoint for getting a list of all our page URLs

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#128]
For tools that move data between other systems (e.g. Internet Archive) and ours, it would be nice to easily and quickly get a list of all the URLs we are tracking, e.g:

```js
GET /api/v0/pages/urls

[
  "http://science.gsfc.nasa.gov/earth/projectsfeatured",
  "https://energy.gov/fe/techlines",
  "http://www.goes-r.gov/users/past-2010-01.html",
  // etc
]
```

The trouble is that querying `/api/v0/pages` and just paging through all the results is slow:

- You can’t change the page size, so this is potentially *a lot* of HTTP requests, no matter how speedy you are.
- Queries aren’t *quite* as speedy as they could be because they include the latest version

Adding the `/pages/urls` endpoint can be simple and fast, though it is kind of a messy extra thing. (Note: could also return tuples of `[uuid, url]` without much impact, too)

That said, it is kinda messy. We could also resolve the above two issues. Part of that is #44, but we also need to resolve the latest version issue. I don’t know whether it would be better to remove it by default and require a `include_latest` query arg (similar to `include_versions`) or to keep the current default and add a `no_versions` query arg (or something along those lines).

@danielballan any thoughts on this?

**Comment by danielballan** [comment]
I agree that a flag is cleaner than a new `/pages/urls` endpoint. I am slightly in favor of a negative default, but if the API change of adding `include_versions` in places sounds painful, I don't feel strongly.

**Comment by Mr0grog** [comment]
W

> but if the API change of adding include_versions in places sounds painful

Eeeennnnhhh, this is why the API is still v0, I think :P

Also we don’t exactly have a broad user-base right now anyway. I’m with you on negative defaults for most things and I’m fine doing it here, too. I’ll make a new issue for that.

Do you think we should close this, then? Even when we make page size customizable, I think we still want a max, so the first issue (lots of requests) will still persist and slowly get worse over time. (That said, our primary use case for this is IA version loading; do you think we’ll eventually move away from wanting to only pull in known URLs…?)

**Comment by danielballan** [comment]
> (That said, our primary use case for this is IA version loading; do you think we’ll eventually move away from wanting to only pull in known URLs…?)

I don't know. This sounds like a problem for v1.

**Comment by lightandluck** [comment]
This still sounds useful. We have this [gist](https://gist.github.com/Mr0grog/40cdcd56b048d7f00b0d47d3aca70be0) that @Mr0grog created, but I don't think he wants to do this manually every time we need an updated list
