### ISSUE TITLE
Fill in `diff_service_version` with data from differ

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#137]
We should fill in the [`diff_service_version` field](https://github.com/edgi-govdata-archiving/web-monitoring-db/blob/master/app/controllers/api/v0/diff_controller.rb#L11) with data from the actual diff response, now that it’s being added there (edgi-govdata-archiving/web-monitoring-processing#89).

Related questions:

- Since we will be copying the `version` field from the response data up one level is the structure of the result, should we remove it from the `content` field? i.e. instead of:

    ```js
    {
      "diff_service": "xxx",
      "diff_service_version": "yyy",
      "content": {
        "version": "yyy" // duplicated info
        "diff": "zzz"
      }
    }
    ```

    We do:

    ```js
    {
      "diff_service": "xxx",
      "diff_service_version": "yyy",
      "content": {
        "diff": "zzz"
      }
    }
    ```

- If yes to the above, should we change to unbox the diff entirely? i.e. instead of:

    ```js
    {
      "diff_service": "xxx",
      "diff_service_version": "yyy",
      "content": {
        "diff": "zzz"
      }
    }
    ```

    We do:

    ```js
    {
      "diff_service": "xxx",
      "diff_service_version": "yyy",
      "content": "zzz"
    }
    ```

- If yes to the above, should we also have a way to do the same if there is other new metadata added? e.g:

    ```js
    {
      "diff_service": "xxx",
      "diff_service_version": "?",
      "content": {
        "diff": "zzz",
        "version": "yyy",
        "something_else": "abc",
        "extra_metadata": "def"
      }
    }
    ```

    to:

    ```js
    {
      "diff_service": "xxx",
      "diff_service_version": "yyy",
      "content": "zzz",
      "metadata": {
        "something_else": "abc",
        "extra_metadata": "def"
      }
    }
    ```

/cc @danielballan

**Comment by Mr0grog** [comment]
We could also move to some more exotic structures, like multipart responses, binary data with a JSON header, or `X-Diff-*` headers, but I think a change of that magnitude should wait until after v0.

**Comment by danielballan** [comment]
I read this and then failed to reply, sorry. What would say to:

```json
{
  "diff_service": "xxx",
  "content": {
    "version": "yyy",
    "diff": "zzz"
  }
}
```

I like this because it delineates "things the service reported" and "things we think we know independently on the response from the service". Any additional metadata goes naturally into `content`. We could alternatively rename 'content' to 'response' but I think either works.

**Comment by Mr0grog** [comment]
I suppose I didn’t propose that because we already have:

```js
{
  "diff_service": "xxx",
  "diff_service_version": "?",
  "content": { /* ... */ }
}
```

i.e. `diff_service_version` is already present in the containing object. That said, it’s hard-coded to `?` (in anticipation of this getting done at some point in the future).

I don’t have a problem getting rid of it since it’s never been meaningful. I just let my thinking be constrained by the old plan. So we’ll do that. No changes except simply eliminating `diff_service_version`.
