### ISSUE TITLE
Add `meta` section to list responses with count of results

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#150]
List-style responses (e.g. `/api/v0/pages`) that are paginated should probably have a [`meta` section](http://jsonapi.org/format/#document-meta) that includes a count of all the results. This would have made writing an API-based script for edgi-govdata-archiving/web-monitoring#74 easier, for example.

**Comment by shishir127** [comment]
@Mr0grog I can help with this but I need more information to understand this. I tried to go through the linked issue but it's too much info to process for a noob like me.

1. The client using this API can just parse the JSON and find out the size of the list e.g. we can invoke `response_body['data'].size` on the parsed JSON reponse of the pages API. Is the `meta` section with a `count` really required here?
2. Can you give me an exhaustive list of which APIs need the `meta` section (assuming it's needed in other APIs)?

**Comment by Mr0grog** [comment]
> The client using this API can just parse the JSON and find out the size of the list

Actually, they can’t! All these APIs are paginated, so a single HTTP response may not contain the entire list of results (you can move through the results using the `chunk` parameter). In the response, the `links` object has important pagination-related info:

- `first` - URL of first chunk of this result set
- `last` - URL of the last chunk of this result set
- `previous` - URL of the previous chunk of this result set (i.e. if you are on chunk 5, this is the URL for chunk 4)
- `next` - URL of the next chunk of this result set (i.e. if you are on chunk 5, this is the URL for chunk 6)

So `meta.count` would be the total number of results across all chunks. e.g. if the `chunk_size` is 100 and there are 3 chunks, there could be anywhere between 201 and 300 results, but you’d only get 100 if you just counted the number of items in `data`.

This is needed on every API that is a list:

- `/api/v0/pages`
- `/api/v0/pages/{page_id}/versions`
- `/api/v0/pages/{page_id}/changes`
- `/api/v0/pages/{page_id}/changes/{change_id}/annotations
- `/api/v0/versions`

**Comment by Mr0grog** [comment]
Fixed in a3a1950455710ec3d854c36cb7a974264b73aa5c
