### ISSUE TITLE
Investigate rails performance improvements

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/web-monitoring-db#154]
Reticketed from https://github.com/edgi-govdata-archiving/web-monitoring-db/issues/119#issuecomment-335305906

Just wanted to create a stub for persons who might go down this path and take a swing at improving performance.

@Mr0grog Am I reading you correctly that you don't think it's a low-hanging fruit situation, and so not worth simply diving in with `rack-mini-profiler` or anything?

Do you think we'd get value only from an expert, or could it benefit from the attention of someone interested in learning about rails performance? (I ask as I was thinking on issues that might be good for [Hacktoberfest](http://hacktoberfest.digitalocean.com/).)

**Comment by Mr0grog** [comment]
> Am I reading you correctly that you don't think it's a low-hanging fruit situation, and so not worth simply diving in with rack-mini-profiler or anything?

No, it could totally be that! In fact, my primary suspicion is that it is either the default JSON serializer; so switching to Oj might be an easy solution, or something about how AR is deserializing from the DB (probably much harder to fix). A simple profiling run would at least tell us where the problem lies.

**Comment by patcon** [comment]
ok rad! I'll add some rando resources that I found, and maybe we could tag this as a first-timer/hacktoberfest!

Some ideas for how this ticket could be acted upon (feel free to open individual issues for these):
- Set up the [`rack-mini-profiler`](https://github.com/MiniProfiler/rack-mini-profiler) for the project and [learn a bit about it](https://github.com/MiniProfiler/rack-mini-profiler#learn-more), then run through [a tutorial using our app](https://www.speedshop.co/2015/08/05/rack-mini-profiler-the-secret-weapon.html)
- Add [Rails performance tests](http://guides.rubyonrails.org/v3.2.13/performance_testing.html)
- Something else of your choosing -- we trust you!

**Comment by weatherpattern** [comment]
Closing. If we need to revisit rail performance we will open a new issue.
