### ISSUE TITLE
Add dotenv gem

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#160]
As a follow-on to discussions in #17, we really should add dotenv to make sure `.env` files get read in automatically instead of requiring people to explicitly `source` them before running the app or rake tasks. Hopefully this will eliminate a lot of simple mistakes.

- Add dotenv gem
- Add info to readme about copying `.env.example` so there’s something for dotenv to use

**Comment by katelovescode** [comment]
I'd like to take this one too for #hacktoberfest! 🙋🏻
