### ISSUE TITLE
Make it possible to forward any diff to a given diff server

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#180]
Right now, we have to explicitly configure each and every diff type, which means that, whenever the `processing` project adds a new diff, we have to at least update the configuration of DB servers (if not also change code), which is kind of ridiculous. It also leads to configuration like:

```sh
DIFFER_LENGTH=http://localhost:8888/length
DIFFER_IDENTICAL_BYTES=http://localhost:8888/identical_bytes
DIFFER_PAGEFREEZER=http://localhost:8888/pagefreezer
DIFFER_HTML_SOURCE=http://localhost:8888/html_source_diff
DIFFER_HTML_TEXT=http://localhost:8888/html_text_diff
DIFFER_SIDE_BY_SIDE_TEXT=http://localhost:8888/side_by_side_text
DIFFER_HTML_VISUAL=http://localhost:8888/html_visual_diff
DIFFER_LINKS=http://localhost:8888/links_diff
```

Which feels pretty darn redundant.

We should support a single env var (`DIFF_SERVER_URL`?) that is used for any unrecognized diff name in:

```
GET /api/v0/pages/{page id}/changes/{change id}/diff/{diff name}
```

**Comment by danielballan** [comment]
In a call, we agreed this is the way to go.
