### ISSUE TITLE
Diff `data` field should be exactly what the diff server sent

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#181]
At current, DB nests the actual diff server’s response in [another object with more metadata](https://github.com/edgi-govdata-archiving/web-monitoring-processing/pull/89#issuecomment-329353425). However, we have since [added diff server version data](https://github.com/edgi-govdata-archiving/web-monitoring-processing/pull/89#issuecomment-329353425) into the diff server’s response and are considering adding more metadata at that level with [a count of changes](https://github.com/edgi-govdata-archiving/web-monitoring-processing/issues/130).

This has lead to some extra-deep structures for the returned data:

```js
{
  "data": {
    "page_id": "9420d91c-2fd8-411a-a756-5bf976574d10",
    "from_version_id": "4b089be5-c6ef-44ce-9a63-fd52443bea3b",
    "to_version_id": "6b600c39-29cd-4fad-9a3a-5edc504f61d8",
    "diff_service": "html_text",
    "content": {
      "diff": { /* actual diff here */ },
      "version": "0+untagged.292.g7062697"
    }
  }
}
```

It also means the structure of a diff returned from DB is very different from that returned from the diff server. Another approach we have talked about is whether the UI could or should talk directly to the diff server.

I think it might be an improvement to merge the DB’s added metadata with the content from the diff server. That at least makes things slightly simpler:

```js
{
  "data": {
    "page_id": "9420d91c-2fd8-411a-a756-5bf976574d10",
    "from_version_id": "4b089be5-c6ef-44ce-9a63-fd52443bea3b",
    "to_version_id": "6b600c39-29cd-4fad-9a3a-5edc504f61d8",
    "diff_service": "html_text",
    "diff": { /* actual diff here */ },
    "version": "0+untagged.292.g7062697"
  }
}
```

We could also restructure this to keep the diff content as much as-is as possible:

```js
{
  "links": {
    "page": "https://api.monitoring.envirodatagov.org/api/v0/pages/9420d91c-2fd8-411a-a756-5bf976574d10",
    "from_version": "https://api.monitoring.envirodatagov.org/api/v0/versions/4b089be5-c6ef-44ce-9a63-fd52443bea3b",
    "to_version": "https://api.monitoring.envirodatagov.org/api/v0/versions/6b600c39-29cd-4fad-9a3a-5edc504f61d8"
  },
  "meta": {
    "diff_service": "html_text"
  },
  "data": {
    "diff": { /* actual diff here */ },
    "version": "0+untagged.292.g7062697"
  }
}
```

**Comment by danielballan** [comment]
Will we be deprecating this route anyway once https://github.com/edgi-govdata-archiving/web-monitoring-ui/issues/146 is in?

**Comment by Mr0grog** [comment]
No? I think we are not as on the same page there as we thought.

**Comment by Mr0grog** [comment]
So I think this is more just me waffling in frustration about a bunch of things. Maybe not really legitimate.

Anyway, I know I have said I don’t like DB sitting in the middle of everything and being a bottleneck, but I also feel like I overall bought into the idea (don’t remember if this came from me or you or someone else at this point) that it was useful to start to think of this project more like “the single, simple API into our data and tools” rather than just a database of changes. I guess I kinda felt like, in service to that, the idea of having UI be able to talk directly to the differ was only really for simpler setup in development, not for production (also the security/abuse concern of anybody being able to ask the differ to hit any URL on the internet, which nobody yet has suggested isn’t a valid issue, so I’m taking it as worth caring about).

I guess maybe that idea (of the separation being only for dev) is a little ridiculous—why put so much work into a code path people would only use in dev and could obscure errors that will occur in production? Having the digging work totally differently in different environments is sure to cause problems. And if we really want DB to be the unifying API, why not prioritize dockerizing all three projects so someone can just `docker up` to get the whole set of services running? I’m not pushing hard n that, but I obviously should be if I want DB to be in the middle and not make dev overcomplicated. And I know I suggested this whole idea of letting U talk straight to the differ, so I’m sorry for this now. I guess I’m just looking at it again and feeling like it’s another sign of us having an unclear and over complicated architectural strategy and finding that enormously stressful. Sorry. /rant

**Comment by danielballan** [comment]
No worries -- I'm fine with shredding my work on edgi-govdata-archiving/web-monitoring-ui#146 if it's the right move, no harm done.

I had not absorbed the idea that was just for dev. Stepping back, I agree that -db should be the "single API to our data and tools." When we were in a phase of frequently updating the set of differs, we may have overweighted the importance of making it easy to update that set. Touching three repos is a bit annoying, but as long as the process is clearly documented in -processing, we can live with it. I expect most future work will involve incrementally improving the differs we have, not frequently updating the set of endpoints.

If you agree, I'll close edgi-govdata-archiving/web-monitoring-ui#146 and work on #16. The 'tmuxinator' YAML file I wrote to solve the `docker up` problem for my local dev setup is a good jumping off point.

Stepping even further back, the broad technical vision for this architecture has fallen to you, and you are also the first responder to urgent deployment problems ("scraping is down!!"). There's no need to be sorry about anything.

**Comment by Mr0grog** [comment]
Sorry for the word salad last night (though I am glad I got it out there). I still feel like this is worth sitting down and talking through. I guess what I *really* want here is to decide on a clear binary about whether we believe in the “single API to our data and tools” idea. I think part of the problem here is us not making a clear, solid decision there (maybe that’s just me, though).

> Touching three repos is a bit annoying, but as long as the process is clearly documented in -processing, we can live with it.

Well, hopefully this issue would mean you don’t have to touch this repo (except to make sure it runs). I do think at least one of either this or edgi-govdata-archiving/web-monitoring-ui#146 is definitely warranted. And I think the situation with differs has definitely changed since the original vision (LOTS of totally independent differs vs. slowly locking down on one diff server), and that is also a factor here.

> the broad technical vision for this architecture has fallen to you, and you are also the first responder to urgent deployment problems ("scraping is down!!"). There's no need to be sorry about anything.

Heh, I guess that just means _I_ need to do better about stepping back from “OMG MUST FIGHT THIS FIRE” and do the *work* of technical vision :P

**Comment by danielballan** [comment]
> I guess what I really want here is to decide on a clear binary about whether we believe in the “single API to our data and tools” idea.

One part I still feel muddy on: The Python webserver is treated as a private REST API used by web-monitoring-db. Is it our long-term plan to lock down the webserver so that web-monitoring-db is its only allowed client? (Seems reasonable to me -- and in keeping with web-monitoring-db as the "single API".) If so, are REST requests the best way to link them? We've discussed this before but I still don't feel solid on it.

> Well, hopefully this issue would mean you don’t have to touch this repo (except to make sure it runs).

Yes, right.

We can get more clarity on both points on the call.

**Comment by Mr0grog** [comment]
> One part I still feel muddy on: The Python webserver is treated as a private REST API used by web-monitoring-db. Is it our long-term plan to lock down the webserver so that web-monitoring-db is its only allowed client?

I think this is probably putting it in a private network, so anything in our suite of services could still talk to it. Another approach might be to have signed keys that allow access to it. So… sort of?

> If so, are REST requests the best way to link them?

So… I think the main thing we’re really talking about *here* is that:

```
GET /api/v0/page/{page id}/changes/{change id}/diff/{diff type}
```

Should effectively be a proxy to the differ (and maybe, given that, DB should add *nothing* to the differ’s response). To that end, I think REST makes sense. I think it’s definitely infeasible to pre-generate all possible diffs and I think systems that handle transactional calls (I want my diff, ok here’s your diff) through queues are kinda nuts (DB puts diff request on queue, differ picks it up, differ puts result on queue, DB picks it up, DB finds any hanging requests for that diff and completes them). But other ways of triggering diffs when the need isn’t transactional still make sense in addition to that (e.g. queues in edgi-govdata-archiving/web-monitoring#62)

**Comment by Mr0grog** [comment]
> We can get more clarity on both points on the call.

👍

**Comment by danielballan** [comment]
Agreed on the call:

```
{
  "links": {
    "page": "https://api.monitoring.envirodatagov.org/api/v0/pages/9420d91c-2fd8-411a-a756-5bf976574d10",
    "from_version": "https://api.monitoring.envirodatagov.org/api/v0/versions/4b089be5-c6ef-44ce-9a63-fd52443bea3b",
    "to_version": "https://api.monitoring.envirodatagov.org/api/v0/versions/6b600c39-29cd-4fad-9a3a-5edc504f61d8"
  },
  "meta": {
    "type_requested": "html_text"
  },
  "data": {
    "diff": { /* actual diff here */ },
    "version": "0+untagged.292.g7062697"
    "type": "html_text"
  }
}
```

where `data` contains the literal response from the differ server.
