### ISSUE TITLE
Handle pages that exist at multiple URLs

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#185]
There’s a more complex version of this in the future (e.g. tracking when a page has “moved”), but for now, we know that many of the sites we track server the same resource over both `http` and `https` and from `www`, `www[number]`, and no subdomain at all. This was first brought up in edgi-govdata-archiving/web-monitoring#82, but we’re going to solve the narrow version of this we are encountering now with IA data purely in DB, hence this issue.

The basic idea, as discussed with @danielballan:

1. Add a field to the `Page` model that is the [SURT-formatted URL](http://crawler.archive.org/articles/user_manual/glossary.html#surt). (See also https://github.com/internetarchive/surt for example code to work from)
2. When importing a version, we look to see if we already have a [Page record for it](https://github.com/edgi-govdata-archiving/web-monitoring-db/blob/master/app/jobs/import_versions_job.rb#L102-L116). That’s done with a lookup based on the URL. Now this will be a multi-step process:

    1. Look for a page with an exact URL match
    2. If no match, look for a page with a SURT URL match
    3. If no match, create a Page
    4. If the page record we have has a “less canonical” URL than the version we are importing, change the Page’s URL to the version’s URL. Most to least canonical:
        1. `https://domain`
        2. `https://www.domain`
        3. `https://www[number].domain`
        4. `http://domain`
        5. `http://www.domain`
        6. `http://www[number].domain`

3. Versions should always have `source_metadata.capture_url` set to the *exact URL they were captured from.*

For now, we expect exceptions where *different* content is served at those 4 URLs to be rare. If we find those situations, we can create a new Page record and move the differing versions to it. Because we look for exact matches *before* SURT matches when importing, imports won’t undo that separation.

**Comment by trinberg** [comment]
I've seen Versionista duplicate pages when the URLs differed by a single "/".

For example:
1) ...domain.gov/subdomain/
2) ...domain.gov/subdomain

Not sure if this is an issue for us, but wanted to note.

**Comment by danielballan** [comment]
Thanks for mentioning that, @trinberg. This does seem like a concern we can incorporate into this issue.

**Comment by Mr0grog** [comment]
It appears [SURT covers the trailing slash case](https://github.com/internetarchive/surt/blob/master/surt/IAURLCanonicalizer.py#L71-L73), so we should be good if we are generally following its design.

**Comment by Mr0grog** [comment]
In this past Wednesday’s meeting we talked about (3) above:

> Versions should always have `source_metadata.capture_url` set to the exact URL they were captured from.

And decided that, instead of adding this to `source_metadata`, we’d add a new field directly on a Version. No name was discussed, so probably still call it `capture_url`.
