### ISSUE TITLE
Add content length and content type to Version

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#199]
I recently added `length` (# of bytes) and `content_type` to the source metadata for Versionista imports (edgi-govdata-archiving/web-monitoring-versionista-scraper#63). These both seem like fields that are important enough to be worth promoting to actual fields on the `Version` object. Should we?

Also, are the above names good? Should they change?

- `length`
- `content_type`

/cc @danielballan

**Comment by danielballan** [comment]
I think we should add them and I think the names are good.

**Comment by Mr0grog** [comment]
Removed the question label; I think this is firmly in confirmed/we-want-to-do-it territory now.

**Comment by Mr0grog** [comment]
Thinking about this more, I’d like to add a third field:

- `length` (# of bytes)
- `media_type` (The `type/subtype` portion of the content type/media type — e.g. `text/html`)
- `media_type_parameters` (Additional parameters for the content type — e.g. `foo=bar; something=else`)

I’m feeling like it would be helpful to separate out the parameters from the main type/subtype for easier querying/grouping/etc. I also changed `content_type` to `media_type`, since that has become the official name for the thing in question (as opposed to the name of the HTTP header).

Should we also have a special field for `charset`? Dunno if that’s going overboard and we should just leave it in the `media_type_parameters` field.

Thoughts?

**Comment by Mr0grog** [comment]
Or maybe we should just drop all the parameters altogether; to get them you’d have to pull the raw content.

**Comment by Mr0grog** [comment]
OK, here’s what needs to happen here:

1. Create a migration that adds the above three fields to the `versions` table.

2. Update `ImportVersionsJob` to be able to populate the above fields from similarly named fields (if present) in each import record.

3. Write a [rake task to populate those three fields](https://github.com/edgi-govdata-archiving/web-monitoring-db/tree/master/lib/tasks/data) in existing records (we no longer mix data migrations with Rails schema migrations):
    - For versions whose `uri` starts with `https://edgi-wm-archive.s3.amazonaws.com` or `https://edgi-wm-versionista.s3.amazonaws.com`, you can make a `HEAD` request and trust that the `Content-Length` and `Content-Type` headers are accurate if present.
    - For other versions, you’ll need to do a `GET` request and read the actual content length. I think it’s OK to not try to sniff the content type if there’s no header for it.
    - This will be a big, slow job, so make sure to write it to operate in batches and only operate on records whose fields aren’t already filled out. Note you *can’t* use ActiveRecord’s `find_each` or `find_in_batches` because they require primary keys to be ordered and UUIDs are not. You can use something like `iterate_batches` method for similar functionality if you need it (sort by `created_at`, since it will always be stable): https://github.com/edgi-govdata-archiving/web-monitoring-db/blob/320efe119257cb8c2b79fbb6f1cbad14b71656b1/db/migrate/20180227024610_add_url_key_to_page.rb#L20-L30

4. If you want to be extra fancy, add a `before_save` callback to `Version` that looks for `;` in the `media_type` field and splits it up to automatically populate it and the `media_type_parameters` field. i.e. if you set:

    ```rb
    version_instance.media_type = 'text/html; charset=utf-8'
    ```

    the callback would have the effect of doing:

    ```rb
    version_instance.media_type = 'text/html'
    version_instance.media_type_parameters = 'charset=utf-8'
    ```

**Comment by Mr0grog** [comment]
Still a very important change we need to get done!
