### ISSUE TITLE
Bad URL in invitation email

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-db#201]
I sent an invitation to staging, and the recipient reported that the URL in the email was incorrect:

```
https://api/users/sign_up?invitation=[REDACTED]
```

**Comment by Mr0grog** [comment]
Yes, that is exactly the issue. E-mails get sent from outside the request/response cycle, so they have no HTTP request to pull a host from. The `HOST_URL` env var is used to provide the “canonical” URL for generating links in jobs and other non-request contexts.

**Comment by Mr0grog** [comment]
I’m going to close this since it’s just a configuration issue in the Kubernetes environment.
