### ISSUE TITLE
Strip 'web-monitoring-db.herokuapp.com' out of the source code.

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-db#204]
Easy to do; I just don't want to forget to do it.

**Comment by Mr0grog** [comment]
Need to figure out whether it should be `api.monitoring.envirodatagov.org` or `api.scanner.envirodatagov.org` or something else (and for the second two, need actually get them set up first).

**Comment by Mr0grog** [comment]
Fixed in #222.
