### ISSUE TITLE
Create and send greeting and usage reminder email when a new Scanner user is created

### ISSUE THREAD

**Issue by weatherpattern** [edgi-govdata-archiving/web-monitoring-db#207]
Starter text:

Hello!

Thank you for signing up to test our website monitoring software, Scanner!

Scanner is currently a work in progress and we'd like to be upfront about various limitations and concerns that we have.

Primarily, we're concerned about erroneous interpretation of changes to webpages that may propagate through social media, news media, or the public more widely. We have seen this happen many times through our work monitoring changes to environmental, climate, and energy websites: https://envirodatagov.org/website-monitoring

In the past, people have  jumped to conclusions from the changes they see on monitored web sites, assuming data is removed based on a single missing link or a temporary bug on a government web server. The changes you see in Scanner are a great jumping-off point for further research, but remember they are not the whole story, especially if those changes are extremely recent.

Scanner may present certain changes wrongly or mislead users in ways that we cannot yet predict or anticipate. We are working to understand these limitations, but for this reason, we are being careful about who gets access to our platform early on. In the long term, we would love for Scanner to be a public platform for all to use, but we'd like to think about harms and impacts carefully before a public release.

Please do not disseminate information about Scanner or share credentials for Scanner. We'd love for you to check it out and give us feedback in any form that you see fit. You can also follow along with our software development work here: https://github.com/edgi-govdata-archiving/web-monitoring

Please get in touch with Ray Cha (@rayc in slack or ray.cha@gmail.com) if you have any questions and we're looking forward to hearing what you think!

To set up your account, point your web browser to:

https://api-staging.monitoring.envirodatagov.org/users/sign_up?invitation=xyz123

**Comment by Mr0grog** [comment]
There are two templates for the invitation e-mail (plain text and HTML-formatted), which can be found in [`app/views/invitation_mailer`](web-monitoring-db/app/views/invitation_mailer). This should be as simple as updated the text in those templates!

**Comment by Mr0grog** [comment]
There are two templates for the invitation e-mail (plain text and HTML-formatted), which can be found in [`app/views/invitation_mailer`](https://github.com/edgi-govdata-archiving/web-monitoring-db/tree/master/app/views/invitation_mailer). This should be as simple as updated the text in those templates!

**Comment by Mr0grog** [comment]
This is important and really just needs someone to execute on it with the above proposed text from @weatherpattern.

**Comment by acaporrini** [comment]
@Mr0grog I made a PR, hope this is still relevant 😄
