### ISSUE TITLE
Handle pages that are tracked by multiple “sites”

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#24]
`site` is currently a property of the `Page` model, but we already know there are a couple pages that are tracked by multiple Versionista sites. So far, we have stored these as separate Page records here, too, but as we are moving towards integrating multiple sources (#15), we need to handle this better. It’s been mentioned before that we should think of sites as something more akin to tags.

A few ideas:

1. Sites as another model with an N:M relationship to pages
2. Sites as a JSON array belonging to a page
3. Have a more generic tagging system and have tags like `site:[site name]` that are applied to pages

This also brings up the question: is `agency` similar? I’m thinking it’s fine as it is now—a direct property of a `Page`—but maybe worth thinking about in this context.

@danielballan Any thoughts on this? I’m thinking either 1 or 3 is best here.

**Comment by danielballan** [comment]
Based on a conversation with @trinberg awhile back, I believe that they'd like to move toward using `site` as a category -- just one per Page. I think agency might eventually grow to tie into a taxonomy of "primers," maybe tied into some parallel work on the Archivers 2.0 app... fine to leave it as is for now.

**Comment by Mr0grog** [comment]
In the April 1 meeting, I think this moved back in the direction of tags, especially as it seems like several people are thinking with an eye towards other organizational and work distribution schemes (see also https://github.com/edgi-govdata-archiving/web-monitoring/issues/30).

I think, based on that, (3) is probably the way to go here.

**Comment by danielballan** [comment]
Agreed.

**Comment by Mr0grog** [comment]
Anecdotally, I was thinking about fixing this as we move quickly towards getting IA data into the system, but discovered we now have 838 pages with multiple sites. Where we used to have no more than two sites on a given page, now some have as many as four.

**Comment by danielballan** [comment]
Shall we move this to the v0 milestone then?

**Comment by Mr0grog** [comment]
Done.

**Comment by Mr0grog** [comment]
OK, going to try and get this done over the weekend. Here’s my plan:

- Add a `Tag` model (and `tags` table) with a many-to-many relationship to `Page` (so there will also be a `tags_pages` table). Tags will have an `id` and a `name`. `name` will be *case-insensitive* everywhere it is used to match or search. The actual value will be stored as whatever case it was first set with (and can be edited).

- Tags will be exposed on pages in the API as a `tags` field that is an array of strings (the tag names) OR at `/api/v0/pages/{page id}/tags`.

- Tags can be added or removed from a page by sending a POST to `/api/v0/pages/{page id}/tags` or a DELETE to `/api/v0/pages/{page id}/tags/{tag name}`

- A list of all tags can be retrieved from `/api/v0/tags` and modified with the usual:
    - `POST /api/v0/tags` (this doesn’t really get you anything more than `POST /api/v0/pages/{page id}/tags` would for now, though. It’ll be more useful in the future when/if we separate permissions for creating tags vs. attaching tags to pages or versions.)
    - `POST/PUT/PATCH /api/v0/tags/{tag id or name}` (Mainly you’d use this to modify a tag name, since there’s not much else to do to a tag.)
    - `DELETE /api/v0/tags/{tag id or name}`

- The `site` and `agency` fields on a page will be removed. Instead, that information will become tags named `site:{value from site field}` and `agency:{value from agency field}`. (We’ll keep the `site`/`agency` fields around in the API temporarily, so for a while you’ll be able to get that info both from the appropriately named fields and from `tags`.)

- Pages that we have multiple records for because of differing `site` or `agency` values will be combined into a single record that has multiple `site:xyz` and `agency:xyz` tags.

- Imports will still recognize `site_name` and `site_agency` fields, but they will be imported as tags.

- Imports will recognize `page_tags`, which should be an array of tags to add to a page.

Some examples…

Anywhere the API returns a page, it’ll look like:

```js
{
  "uuid": "0010ec22-eec8-4c2d-b9bb-d486be7a4d9a",
  "url": "https://www.epa.gov/re-powering/re-powering-benefits-matrix",
  "title": "RE-Powering Benefits Matrix | RE-Powering America's Land | US EPA",
  "created_at": "2017-05-09T05:41:45Z",
  "updated_at": "2017-12-18T17:02:05Z",
  "tags": [
    "agency:EPA",                 // this page used to have the field "agency": "EPA"
    "site:EPA - epa.gov/energy",  // this page used to have the field "site": "EPA - epa.gov/energy"
    "PDF Abstract"                // just a potential tag someone might add
  ]
}
```

Listing tags with `/api/v0/tags`:

```json
{
  "links": {
    "first": "https://api.monitoring.envirodatagov.org/api/v0/tags?chunk=1",
    "last": "https://api.monitoring.envirodatagov.org/api/v0/tags?chunk=3",
    "prev": null,
    "next": "https://api.monitoring.envirodatagov.org/api/v0/tags?chunk=2"
  },
  "meta": {
    "total_results": 210
  },
  "data": [
    {
      "id": 1,
      "name": "agency:EPA",
      "created_at": "2017-05-09T05:55:33Z",
      "updated_at": "2017-12-27T09:20:26Z"
    },
    {
      "id": 2,
      "name": "site:EPA - epa.gov/energy",
      "created_at": "2017-05-09T05:55:33Z",
      "updated_at": "2017-12-27T09:20:26Z"
    },
  ]
}
```

Add a tag to a page: `POST /api/v0/pages/0010ec22-eec8-4c2d-b9bb-d486be7a4d9a/tags` with body:

```json
{
  "name": "PDF Abstract"
}
```

Rename a tag: `POST /api/v0/tags/PDF%20Abstract` with body:

```json
{
  "name": "PDF Landing Page"
}
```

Feedback welcome!

**Comment by trinberg** [comment]
Thanks, @Mr0grog - this all makes sense and I think will give us more control organizing sites/pages.

I guess this may not affect things now, but let me know if it does. I think we eventually want to map all our sites/domains to this "Agency Office Database" that @mayaad, @ambergman, and I started to help coordinate the archiving events: https://docs.google.com/spreadsheets/d/10NBGu3_cIbapC5RiDiJFY5Ypqj8idiqk4z7NIJ3K5I0/edit#gid=475805335 - we realized and hoped that this will be useful to organize website monitoring/archiving efforts down the line.  

Essentially it's a relational database built out of various agency org charts. I think it'll be totally compatible with the tagging system - the idea would be to just tag each page with the most specific code that we have. I'm sure folks have thought about systems like this before, so I wanted to note this now in case there's thought going into it.

**Comment by Mr0grog** [comment]
OK, so now I am very unsure tags are the right answer for this problem. You’ve got a lot of rich data there that tags certainly won’t handle well, @trinberg. I don’t know if we are actually going to want any of that in this DB, but if we ever do, we’ll have to transition to a new model from tags to support it.

**Comment by danielballan** [comment]
Tags seem like a good place to put some information, such as the "PDF Abstract" example above, and I think they will be useful long term. Separately, I agree with @Mr0grog that the taxonomy of government organizations does not fit into a tag model, but I think that is somewhat orthogonal to this issue. Adding tags won't help us incorporate the taxonomy, but I don't think it will make incorporating it any _more_ difficult. I propose we go ahead with tags and worry about the taxonomy post v0.1.

**Comment by danielballan** [comment]
I wrote the above comment before catching up on #206. I'm fine with going forward that way.

**Comment by Mr0grog** [comment]
OK, we did a call today with @danielballan, @trinberg, @weatherpattern, and myself to discuss this.

Talked about doing it all with tags, doing it all with specialized models (e.g. #206), a mix of the two, and also a very interesting concept of a table of “links” (like tags, attachable to many things, and in a many-to-many relationship), which would be a sort of linked data idea, where each one is a name, type, and URI to a resource in another database or on the web (in this case, a separately maintained DB of agencies) (we decided this last one was neat, but maybe a little abstract and/or reaching a little far).

## Decision:

1. Add a `Maintainer` model which has a many-to-many relationship with `Page`. This replaces `agency` on a `Page`. It’s renamed because:
    - “Agency” is already over-specific; we are using it for things that are actually bureaus, departments, offices, etc.
    - “Maintainer” also works in the broader context of other types of organizations besides government, since we want to be friendly to the software’s re-use where possible.
    (Other names floated included “administrator,” “administrative_level,” “administrative_unit,” “organization,” “owner”)

2. Add a `Tag` model which has a polymorphic (can be attached to more than one type of thing) many-to-many relationship. It’s only related to `Page` for now, but we could add it to anything with a UUID. A page’s `site` field will be replaced by a tag named `site:{value of old site field}`.

    We don’t think there’s enough useful meaning or data in the particular case of Versionista “sites” (where our current concept of “site” comes from) to warrant it having much more than a name. Even in Versionista, it’s mainly an organizing concept (it doesn’t actually relate to a domain name, for example), so we may as well use it as a point through which to introduce tags, which lets us easily try out *other* organizing concepts.

**Comment by danielballan** [comment]
Well summarized. Thanks for writing up the call.
