### ISSUE TITLE
Document how archiving and `ALLOWED_ARCHIVE_HOSTS` work

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#249]
The configuration around data sources is confusing users trying to get everything set up. We should clarify what goes with `ALLOWED_ARCHIVE_HOSTS` and importing/archiving in general.

**Comment by Mr0grog** [comment]
See also #158.

**Comment by danielballan** [comment]
:+1: :+1: :+1: :+1: :+1:

**Comment by jsnshrmn** [comment]
Still relevant and on my to-do list.
