### ISSUE TITLE
Remove `include_versions` from `/pages` and versions list from `/pages/{id}`

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#264]
We have a nice, clever `?include_versions` querystring argument for the `/pages` route that causes each page object in the response to include a list of all its versions. We kind of knew that might be a problem down the road as we accumulated lots of versions, but with some pages now importing a lot of historical versions from Internet Archive, it’s going to be untenable very soon.

We should probably get rid of this option.

Alternatively, we could something like the N latest versions, where N is something like 10. If we did this, it might make sense to go further down the json:api route and classify them as relationships:

```js
{
  "links": {...},
  "data": [
    {
      "uuid": "1574d802-fd13-4699-881d-f0f8a7d45a79",
      "url": "https://www.fws.gov/refuges",
      "title": "National Wildlife Refuge System",
      "agency": "DOI",
      "site": "DOI - fws.gov",
      "created_at": "2017-05-09T05:26:41Z",
      "updated_at": "2018-03-28T05:31:57Z",
      "url_key": "gov,fws)/refuges",
      "maintainers": [...],
      "tags": [...]
      "relationships": {
        "versions": {
          "links": {
            "self": "https://api.monitoring.envirodatagov.org/api/v0/pages/1574d802-fd13-4699-881d-f0f8a7d45a79/versions",
            "first": "...",
            "last": "...",
            "next": "...",
            "previous": null
          },
          "data": [
            { /* version record */ },
            { /* version record */ },
            { /* version record */ }
          ]
        }
      }
    }
  ]
}
```

(But then maybe we ought to go back and fully implement json:api, and 💩 to me for not doing it right the first time around.)

**The same goes for the `/pages/{page ID}` route,** which always includes a `versions` property. It should also be removed or follow the same rules as above. (Maybe we could replace it with a `latest` and `earliest` property?)

/cc @danielballan @lightandluck @weatherpattern

**Comment by weatherpattern** [comment]
Thoughts and some questions.
I agree that we should get rid of the `?include_versions` querystring argument and the versions list to save people from mistakenly requests way more data then they realize.

1. Are these features being used anywhere currently, like in Scanner or other scripts?

2. If we drop these features, how would someone get the full list if they needed it?

3. If we have to fetch each version one at a time, how would that impact the performance of Scanner?

**Comment by Mr0grog** [comment]
> Are these features being used anywhere currently, like in Scanner or other scripts?

`?include_versions` is used to generate analysts’ weekly spreadsheets (it avoids the performance problem by always scoping the results to a small time window and asking for fewer than the default `chunk_size`). This change will slow it down a lot.

The versions list that is automatically included in `/pages/{page id}` is used by the UI.

> If we drop these features, how would someone get the full list if they needed it?

Using the API designed specifically for listing versions: `GET /versions` or `GET /pages/{page id}/versions`.

> If we have to fetch each version one at a time, how would that impact the performance of Scanner?

That is not a thing we have to do.

**Comment by Mr0grog** [comment]
> [The analyst spreadsheet script] avoids the performance problem by always scoping the results to a small time window and asking for fewer than the default chunk_size

As noted in the OP, another workaround is to support `?include_versions` as a “relationship” in json:api terms and severely limit how many are returned, e.g. 10 (instead of the current behavior, where it’s not a relationship, just a list, and it includes *every* version). On the DB side, that will necessitate a much more complicated and slower query, but it’s most likely still faster than the overhead of multiple HTTP requests.

Note: the “relationship” idea is important if we want to truncate the list because that structure supports all the links and other metadata that let someone *know* the list is truncated and provide a clear way to get to the next chunk of the list.

**Comment by weatherpattern** [comment]
Given your answers, I don't know if we should at this time fully implement the json:api. What level or work is that? 

If we don't go the full json:api route, I think we should remove the option as you recommend, but include go with the relationships idea because those fields have obvious use. Is it common / helpful to also include in that a total count of the number of versions?

**Comment by lightandluck** [comment]
To sum up my understanding of convo at 4/4 meeting:
1) We'll go with what's proposed and remove that query string option
2) To replace that functionality we'll want to implement the json:api spec and make it into a relationship object. This is probably two separate issues which both would take some time and have impact on clients using the api, so if we want to do it we should before people start using it. But we won't be able to address it right now.
3) We'll have to adjust how the analysts sheets are made and how Scanner grabs versions on the details page

**Comment by Mr0grog** [comment]
Question: if someone uses the `?include_versions` argument, should we ignore it or return an error saying it’s been removed?

**Comment by lightandluck** [comment]
I'd say return an error. It would help us find anything we might have forgot about.

**Comment by lightandluck** [comment]
And help out that 1 in a billion person, who might be using it 🎲

**Comment by danielballan** [comment]
Agree with @lightandluck. Seems like an application that passes `include_versions=1` is likely to fail downstream if the response silently omits Versions. Better to fail early with a clear error.

**Comment by Mr0grog** [comment]
Makes sense to me!
