### ISSUE TITLE
Imports should have a `?create_pages=true|false` querystring argument

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#265]
## Background

In the new IA bulk import script, we try to be efficient by querying for all snapshots in a given domain for the time period we’re concerned about. Unfortunately, that means we will almost certainly pick up snapshots for pages we don’t care about. We might want those in the future, but not right now. This presents a problem:

- We can’t filter the responses based on exact URL matches because we know multiple URLs correspond to a single page, e.g. `http://www.epa.gov == https://www.epa.gov`

- We are currently filtering on [`url_key`](https://github.com/edgi-govdata-archiving/web-monitoring-processing/pull/174/files#diff-b12cfc8d93e2d8ce1cf3f93ea9809cb8R80), but that only works because our canonicalization method happens to be modeled after Internet Archive’s. The problem is that we might have good reason to change our canonicalization in the future or Internet Archive might change theirs. We can’t always expect these to match up — even though it *mostly* works right now.

- We can’t canonicalize the URL we got from IA according to our rules on the fly because the import script is not part of the DB API. Even if they were in the same language, so we could share the code (they aren’t, so we can’t), we wouldn’t have any good guarantee that the version of the import script you’re using matches up with the version of the DB API you are sending data to.

So… I kinda feel like we have to filter out versions and determine whether to add them as part of the actual importing process *here,* inside the DB API.

## Proposal

I propose we add a `?create_pages=true|false` querystring argument that controls whether new page records can be created if the version to be imported doesn’t match up to any existing page. The default behavior would be `true`, which is how the importer currently behaves (if the the version doesn’t correspond to an existing page, we create a new page for it). If `false`, we simply wouldn’t import the version.

It’s a boolean argument, so if there’s no value at all (i.e. no equals sign), that’s equivalent to `true`:

- `?`, `?create_pages`, `?create_pages=true`, `?create_pages=TrUe`, `?create_pages=1` are all `true`
- `?create_pages=false`, `?create_pages=FaLsE`, `?create_pages=0` are all `false`
- Other values are errors

**Comment by Mr0grog** [comment]
> Under what current circumstances would this be turned off?

Importing data from Internet Archive, where the script sending versions to the DB is not capable of accurately filtering it.

**Comment by lightandluck** [comment]
+1 for moving forward with what was proposed
