### ISSUE TITLE
Add a `?skip_unchanged_versions=true|false` querysting argument to /imports

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#266]
## Background

When importing data from Internet Archive (or any source, really), we only know about data in the timeframe we are examining. If a data source (like Internet Archive) doesn’t differentiate between versions that are the same and versions that are different from the ones that precede them, we could wind up importing a version to our database that is no different from the latest version we already have. This is undesirable when we are *generally* trying to only store versions that differ from the version before them (in the long run, that might be worth revisiting, but for now, it’s what we’re doing). We don’t make any guarantees about that, but we try to make sure it’s true in most cases.

For example, suppose our database has versions of the page `http://ugabooga.com/whiz-what-wow.html` like:

| capture_time | hash |
| ------------ | ---- |
| 2018-01-03   | abc  |
| 2018-01-05   | def  |
| 2018-01-20   | ghi  |

And Internet Archive captures a snapshot of that page every day. If the page never changes after 2018-01-20, but we run a script on 2018-01-21 to import new versions, we’ll bet back a version record from Internet Archive like:

| capture_time | hash |
| ------------ | ---- |
| 2018-01-21   | ghi  |

It’s exactly the same content as the latest version we already have (it has the same hash), but looks like a new record because it was captured on a newer date.

At current, we will store this version, which means our API will show two consecutive versions that are exactly the same :(

## Proposal

I propose we add a querystring argument to `POST /imports` called `?skip_unchanged_versions` with a boolean value. If set to `true`, the importer would not import versions of a page that have the same hash as the version captured immediately before them (*from the same source*).

The default value for it would be `false` — matching existing behavior, but also playing it safe. If `true`, we have to guarantee that the versions in the import request *are in capture_time order* (otherwise we might skip them incorrectly).

## Alternatives

We might start storing all snapshots of a page (regardless of whether they are different from the previous), but add a special field named `changed` (or `is_changed` or `is_different` or something similar). That field would be a boolean indicating whether that version’s hash matches the previous version’s hash, and we’d use it when querying to determine whether to show a version.

This is a lot more complicated than simply not importing things:

- We have to make sure the special database field stays up-to-date and accurate whenever adjacent versions are added
- We have to make sure all our queries correctly check that field so they are showing the right things
- It potentially has much higher storage costs (because we’ll store a *lot* more versions)

On the other hand, it’s also a lot more flexible (and safe). ¯\\\_(ツ)\_/¯

/cc @danielballan @weatherpattern @lightandluck 

*File under: this project is slowly becoming a miniaturized archive.org*

**Comment by Mr0grog** [comment]
> the alternative is also reasonable and increased flexibility is over good

This is what the “slowly becoming a miniaturized archive.org” comment was about :P

Sorry that was probably not clear without some assumed knowledge about how our imports work and how archive.org’s APIs work.

**Comment by weatherpattern** [comment]
All good. The joke raises an important point, which was well taken. A little humor in git is a good thing.

The more we store from IA highlights the trade off being having more control over the data and performance. I'd be hesitant to store nothing on our own, but the right amount is good question.

Would the increased amount of data run the risk of outspending our S3 storage grant for the year?

If we go with your proposal, and default to off, when would we need to turn it on?
Maybe the path forward is to go with your proposal and then, in the short/mid term we can solve the issue of too many versions through the UI.

A related question, is it helpful to frame our decisions, that our goal is to try to maintain parity the data the analysts have now in Scanner?

**Comment by Mr0grog** [comment]
> Would the increased amount of data run the risk of outspending our S3 storage grant for the year?

Hahahahahaha, even with extra costs from all the analyses and updates I ran this month (#205 and edgi-govdata-archiving/web-monitoring#95), our total **S3 + Bandwidth costs are $4.27 + $7.38 = $11.65 for this month** (and that’s a slight over-estimate because they’re [still in my account](https://github.com/edgi-govdata-archiving/web-monitoring/issues/101) which has other activity going on). That cost is pretty negligible, even if we multiplied it by 5 (and that’s not *too* likely, since we store non-versionista content by its hash, which means we don’t store duplicates).

> If we go with your proposal, and default to off, when would we need to turn it on?

For all imports where we don’t know if the version we are recording is the same as a previous version (right now, that’s just IA, but it’s possible more potential sources would fall under that umbrella than not).

> is it helpful to frame our decisions, that our goal is to try to maintain parity the data the analysts have now in Scanner?

I don’t feel like that’s especially relevant. They’re already familiar with having to dig through IA data manually without *any* tools (except their eyes) to tell them whether there’s a change, and even if we did nothing more than we currently do in scanner, we’d be better than that (because we have the little banner that warns them if the versions they are looking at are identical).

**Comment by weatherpattern** [comment]
Thanks for your answers.
 
Even if cost isn't an issue, then my take is to still go with your proposal, keep it simpler, and with IA if there are lots of version, I think so we deal with that in the UI. But definitely open to other's opinions.

**Comment by Mr0grog** [comment]
> my take is to still go with your proposal, keep it simpler, and with IA if there are lots of version, I think so we deal with that in the UI

I’m confused now. The main proposal is simpler (the alternative has open questions that could make it simpler or more complicated, but most likely more complicated※), but it is also the one that means having the least extra data from IA that might be hard to deal with in the UI. The main proposal is to add a mechanism to the importer that causes it to *not import* versions that are not different from the latest version we already have of the same page. That means importing the *least* we can from Internet Archive.

- Worth noting again if it was not clear: there are lots of situations where we could wind up importing duplicates or missing versions we should have captured because this feature makes imports behave differently depending on what’s in the database. That is, everything *must always happen in order* when using this feature. It does not make any safety guarantees like the current system generally does. As noted in the proposal, that is why it would default to `false`.

---

※ Open questions in the alternative, to put them explicitly:

- Do we need the proposed flag about whether the version was a change?
    - Not adding it is simple: we do nothing. It is less work than the primary proposed change.
    - Not adding it would cause a change from the existing semantics of a “version” (now versions would just be “captures” or “snapshots”)
    - A sufficiently smart client (like the UI) could live without it by checking the `version_hash` of consecutive versions (which is all the flag would be; it would just be *pre*-computed)
    - Some questions would be much harder to answer without it (e.g. “what changed [in this timeframe]?”—the query we use to generate weekly sheets)
    - Adding it makes importing more complicated (we have to add a post-processing step to recalculate the flag on all versions around the ones that were imported).
    - Adding it *potentially* makes all the query logic for pages and versions more complicated (see questions below about whether we’d add filtering).
    - If we make querying with it more complicated, adding it means clients don’t have to make any changes. (Again, see below about whether we’d add filtering.)
- What would the flag be named if we added it?
- Would we add the capability to filter queries based on the flag? Would filtering by it be on by default (so nothing changes for clients; it’s backwards-compatible)?
- Should we rename “versions” to something else, e.g. “captures” or “snapshots?” (See second sub-point above about changing semantics)

**Comment by weatherpattern** [comment]
Sorry for the delay and any confusion. I think I understand the trade off better now.

I still am leaning towards simpler being the better way to go, and overall less data is ok. It will never be perfect, I think we can pause on replicating the wayback machine for a bit longer.

**Comment by gblike** [comment]
If I am following correctly, I like the proposed idea (not the alternative). If we really want to store more data, we should just observe the sites ourselves and skip the middleman.

What I don't like about using IA or Versionista is that they act as proxies to the actual act of observation. I would like to record some information about who and what observed the site and metadata about the observation (Eg timestamp). Observations should have duplicates if nothing has changed on the site, but versions should involve a change for each one. Duplicates should only exist if they are non-consecutive.

**Comment by Mr0grog** [comment]
> If we really want to store more data, we should just observe the sites ourselves and skip the middleman.

So, just to be clear, the main concern I am trying address in the alternative proposal is not having more data (though that adds some utility, too), but *safety.* I’ve mentioned this a few times already but nobody has remarked on it, so I want to make sure people are hearing it: we have no system for guaranteeing that imports are processed in order (or that versions listed in an import are in capture time order). If we get imports out of order, there is a high probability we will drop versions we should have recorded or record versions we should not have.

Most of the time this is no problem because we only have one import worker (in production; staging actually has two, which poses a problem here) and because our current imports are both relatively small and relatively quick, so we rarely have two ready to run at the same time. That said, whenever we are remediating old data, we have things coming in out of order by definition. This isn’t theoretical; we’ve had to do it a number of times.

(That said, I don’t want to *over-sell* this concern. How many versions will we screw up if we hit this problem regularly? Probably not many. The question is: how many errors are acceptable and what’s our likelihood to cross that threshold?)

In terms of just having more data, though, there is also a really big data benefit in having a record of every capture/snapshot/observation/sample: analysts regularly head over to the Internet Archive to try and get a better sense of when a change may have actually occurred (so: this is not a theoretical concern). If all you have is a record of the first time a difference was *observed,* you don’t have a very clear idea of when that difference came into being. If you know all the observation times in-between, it’s possible to get a much more accurate time for the change (how accurate depends on how often you made observations, of course). But again, my chief concern before this is safety. The safety-focused approach just happens to have this side-benefit :)

> Observations should have duplicates if nothing has changed on the site, but versions should involve a change for each one.

Totally agree, which is why I pointed out this would be an important change in semantics and potentially deserves a change to the name of the object.

That said, it is important to keep in mind that ensuring every consecutive version is different from the previous, when lined up in `capture_time` order, is *not a guarantee we can or do make* because we admit historical data (and data form sources we do not control). Our timeline is by design not an immutable merkle-linked-list. We currently try to make sure versions are different from their predecessor the vast majority of the time, but *only within a given `source_type`.* We can guarantee that for Versionista, but only because Versionista can guarantee it to us (because they don’t adopt historical data they did not record in real time).

**Comment by weatherpattern** [comment]
OK, I wasn't explicit but I am willing to accept taking on some technical debt (and missed versions/duplicate versions). I don't think we can afford to hours for alternative solution. That said, we should document that it is best to only run one importer job for the reasons you describe. We can add your alternative in a new issue to tackle at a later date.

>  The question is: how many errors are acceptable and what’s our likelihood to cross that threshold?

 I presume that this is a rhetorical question, but an important one.  I think if we discover that number of errors not acceptable, we can escalate the new issue. 

What do you think @lightandluck  ?
