### ISSUE TITLE
Add routes to download raw import records and import logs

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#278]
This is closely associated with #191. We currently store import records indefinitely, but they are not publicly exposed (you have to have access rights and you have to know where to go grab them from). 

Should we expose them via the API?

If we do so, does that mean we have to commit to keeping them forever, or would it still be OK to delete old ones? (We don’t actively do that right now, but the intention was that we always could to save costs).

Possible API ideas:

- `GET /imports/{id}/raw` or `GET /imports/{id}/data` to get the POSTed import data.
- `GET /imports/{id}/log` or `GET /imports/{id}/results` to get the logged results of an import (see #191 — these files don’t actually exist yet)

Based on conversation in #277. /cc @danielballan

**Comment by Mr0grog** [comment]
> For our deployment, I would suggest compressing these logs

Oh, we should really do that with the POSTed data, too.

> What about `GET /imports/{id}/request`?

The more I think about it, the less I like `/raw`.

`/request` is interesting. It *could* be more clear than `/data`, but only if you happen to read it right (as a noun—the request that generated this import—rather than a verb or a thing belonging to the import). I think I’m leaning towards `/data` here.

> I like `GET /imports/{id}/log` better than `GET /imports/{id}/results`.

👍

**Comment by danielballan** [comment]
Fair point about noun/verb ambiguity. I accept `/data` as a good consensus choice.

**Comment by Mr0grog** [comment]
Cool, I think we are at a solid design here, then:

Two new API endpoints:

- `GET /api/v0/imports/{id}/data` returns either:
    - `200` with the original data that was sent to `POST /api/v0/imports` to be imported
    - `410` to indicate the original data has been garbage collected and is no longer available
- `GET /api/v0/imports/{id}/log` returns either:
    - `400` with a normal API error (`{errors:[{title: 'This import is still pending'}]}`) if the import hasn’t been run yet
    - `200` with an ND-JSON stream of all the structured logs created during the import
    - `410` to indicate the log has been garbage collected and is no longer available

Supporting the `410` means we make no guarantee that logs (or data) will be available indefinitely (though we have no plans to delete at the moment).

Data and logs will be stored and may be delivered gzipped.

Work to be done:

1. Add the above to docs
2. When [creating an import with data](https://github.com/edgi-govdata-archiving/web-monitoring-db/blob/master/app/models/import.rb#L12-L16), gzip the data (maybe requires some filestore changes, too)
3. Add the `/data` route above
4. Add the `/log` route above after #191 is done

**Comment by Mr0grog** [comment]
@bensheldon is doing the preliminary work for this in #551, and then we should definitely tackle this.

**Comment by Mr0grog** [comment]
We are no longer planning to do this — a real-world use case has never arisen for it (in all situations where this is really necessary, or logs are enough), and saving special log files to support it is a lot of extra special code. See this comment for more: https://github.com/edgi-govdata-archiving/web-monitoring-db/issues/191#issuecomment-548517013
