### ISSUE TITLE
Be more verbose when importing seed data

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/web-monitoring-db#291]
Right now, running `bin/rails db:seed` can take quite some time, and doesn't give feedback on progress. For example, looking at `seed_import.json`, I see that there are 1000 lines, but even with that knowledge, I'm unsure how quickly things are progressing.

Feedback every few seconds would help people understand that everything is going as planned :)

**Comment by Mr0grog** [comment]
This was fixed by @bensheldon in #529! 🎉
