### ISSUE TITLE
Swagger form on home page always calls production instead of the server it is running on

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/web-monitoring-db#292]
## Steps to reproduce

1. Setup locally
1. Did partial import of seeds. (ran for 15 minutes, but had to abort, assuming there's be some data in the database?)
1. Logged in via credentials in seeds.rb: https://imgur.com/893yWlU
1. Tried to execute to test `GET /pages` via UI with default params

## Expected Behavior
Expected to see some response with data

## Current Behavior

Got: `401 Error: Unauthorized` message

## Your Environment
Running through Heroku backend services (see other PR), because my system has issue :)

Any thoughts?

**Comment by Mr0grog** [comment]
> Tried to execute to test GET /pages via UI with default params

How did you execute the GET?

> Seems like maybe even locally, the base url points to the live website?

I’m not sure what the base URL would be here. Can you give some more context?

**Comment by Mr0grog** [comment]
Oh, sorry, I missed the part about using the UI. Is your UI configured to point to your local DB? (See [install step 4](https://github.com/edgi-govdata-archiving/web-monitoring-ui#installation) and the [example `.env` file](https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/master/.env.example#L1-L2)) If you don’t configure it, it will default to staging.

**Comment by patcon** [comment]
> How did you execute the GET?

Via my local swagger web ui

> I’m not sure what the base URL would be here. Can you give some more context?

https://imgur.com/Lb2oPhp

(I changed the "host" key in swagger.yml from the live endpoint to localhost, but in current codebase, the local swagger ui makes call to the live api, which was a bit confusing: https://github.com/edgi-govdata-archiving/web-monitoring-db/blob/master/swagger.yaml#L12

chrome inspector confirmed that this was what was happening :)

**Comment by patcon** [comment]
Ok, got it working, but had to set `host: locahost:3000` and `schemes: ['http']`

**Comment by Mr0grog** [comment]
Oh, in the *Swagger UI.*
