### ISSUE TITLE
Small typo in invitation email url

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/web-monitoring-db#301]
Friendly point to this minor thing. Note the double-slash. Spent some time looking, before realizing it's prob a trailing slash in an envvar :)

https://api.monitoring.envirodatagov.org//users/sign_up?invitation=5210fdbd465fbcee5cdf

(Invitation code already used!)

![screen shot 2018-04-24 at 1 45 07 am](https://user-images.githubusercontent.com/305339/39168272-39f68238-4761-11e8-8090-b339dba63afa.png)

**Comment by Mr0grog** [comment]
We should update production config, but probably good to handle an incorrect config by using `chomp('/')` when we setup action mailer (in `/config/environments/*.rb`):

```rb
ENV.fetch('HOST_URL', 'localhost').chomp('/')
```
