### ISSUE TITLE
Add an authorization system

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#34]
Right now, we have a special `admin?` flag on users that mainly controls whether they can get into the admin area to invite or delete users. We should make the permissions system a little more granular and separately grant users:

- Admin capability
- Permission to annotate versions
- Permission to import/create versions/pages

For safety, we probably want services that import things to *only* be able to import and not create annotations, while we might want most users to *only* be able to create annotations but not import.

**Comment by danielballan** [comment]
Additionally, we need to differentiate between non-admins who can annotate and who can only view. This might play into tasking too.

**Comment by danielballan** [comment]
Useful gems:

* cancancan
* pundit (probably better according to @Mr0grog)

**Comment by Mr0grog** [comment]
Note we now also need permission to:

- view annotations
- view at all (I think, so long as no data is just plain public yet, we want a permission for this, if for no other reason than so we can shut it off for a malicious user.)

**Comment by Mr0grog** [comment]
Related question for viewing annotations—can a user who can’t view annotations see that there were annotations made on a given change? Easy answer is probably no, but worth at least clarifying here.

**Comment by danielballan** [comment]
At the lowest level, we should probably make these distinctions as granular as possible and then exposed them bundled together into a small number (3-4) of roles, to make adjustments easy to make quickly.

**Comment by Mr0grog** [comment]
Note also part of this is returning permissions in the API. This should probably be in `User#as_json` (which could be automatic depending on how things are implemented) or somehow added directly in the responses for `Users::SessionsController`.

We could also consider surfacing permissions in our JWT auth tokens. That might make them pretty big, though.

**Comment by danielballan** [comment]
Do we actually need this for "v0"? I think we do need to address #122 (auth everywhere) but that the admin/non-admin distinction is sufficiently granular for now.

**Comment by Mr0grog** [comment]
I think we do because UI now has a [really horrible hack](https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/master/src/components/change-view.jsx#L98-L105) that makes it hard to work on annotations until this is fixed. I’d have recommended @lightandluck make that part of app configuration instead if I thought we were going to defer this.

**Comment by Mr0grog** [comment]
That’s not to say we can’t go back and change UI to show/hide that form based on configuration instead, but I kinda feel like it’s a useful forcing function to get this important functionality done. We can also piggy-back on this auth/permissions feature to do feature flags, which will be extra useful in the future. I can take this back if you need to be freed up to focus on differ work.

**Comment by danielballan** [comment]
Fair point that it is a useful forcing function.

> I can take this back if you need to be freed up to focus on differ work.

On the one hand, I should hang onto this in my continuing quest to dust off / update my Rails chops. On the other hand, I'm sure you could dispatch this more quickly, and my skills would be better used over on -processing.

How about: whoever starts in on it first, post here.

**Comment by Mr0grog** [comment]
This is back on the short-list because we need it for edgi-govdata-archiving/web-monitoring-ui#220, which we want to push harder on now (right after Wayback import work). We’ve been too willing to let the whole category of “be more open” slide.

For the public demo — which really just means making a staging account anyone can use — the main permission we need is for importing (we need to avoid having all kinds of people throwing  a giant pile of data at us).

**Comment by Mr0grog** [comment]
Still critically important.

**Comment by bensheldon** [comment]
FYI, I will work on this 🏭 

Based on this issue and conversations, I am proposing the following permissions:

- `manage_users` - Invite, and delete users and manage their permissions (current "admin" role)
- `annotate` - View and create annotations
- `import` - import or create versions and pages
- `view` - See versions and pages (suggested the ability to "shut off" a user without deleting them)

Please give feedback on this as a v1. We can defer additional granularity (e.g. splitting viewer and editor) once we have it in place.

**Comment by Mr0grog** [comment]
This sounds fantastic and spot-on. Thank you so much for taking this on ❤️
