### ISSUE TITLE
Admin users list needs to allow promoting/demoting admins

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#355]
When the current logged-in user is an admin, the admin users list at https://api.monitoring.envirodatagov.org/admin desperately needs to display whether each user in the list *is* an admin and allow promoting other users to admin (or demoting them from admin). Continuing to do this through the Rails console isn't really good enough; it locks out some folks who should have admin rights but don’t have (or are unwilling to exercise) that expertise.

This requires some new actions in the [`AdminController`](https://github.com/edgi-govdata-archiving/web-monitoring-db/blob/master/app/controllers/admin_controller.rb), new [routes to those actions](https://github.com/edgi-govdata-archiving/web-monitoring-db/blob/34f3f9644e19f149ffbf6746673a3d141c1bc531/config/routes.rb#L37-L43), and updating [`app/views/admin/index.html.erb`](https://github.com/edgi-govdata-archiving/web-monitoring-db/blob/master/app/views/admin/index.html.erb) to add the UI.

Check out how the `destroy_user` and `invite` actions work for examples.

Future work might move all this admin stuff into the actual `/api/v0/{whatever}` routes, but for now let’s keep this with all the other admin stuff, which isn’t included there.

**Comment by acaporrini** [comment]
I would like to claim this issue

**Comment by Mr0grog** [comment]
Great, thanks!
