### ISSUE TITLE
Allow for arbitrary hostname:port, md5 authentication in development and test environments

### ISSUE THREAD

**Issue by jsnshrmn** [edgi-govdata-archiving/web-monitoring-db#358]
Discussion about this started in https://github.com/edgi-govdata-archiving/web-monitoring-db/pull/294
Currently, I'm only able to run this project in development and test environments if postgreSQL trusts the connection rather than challenging for a password.

## Expected Behavior
I'd expect to be able to configure some environment variables that allow me to develop this project against a password-protected database running on an arbitrary host:port.

## Current Behavior
Connections for development and test environments always unauthenticated requests to localhost on the default port.

## Possible Solution
The most straightforward way to do this is to parse DATABASE_URL and set some defaults based on that. PR forthcoming.

## Steps to Reproduce (for bugs)
1. set RAILS_ENV="development"
2. set pg_hba.conf to md5 auth instead of trust.
3. set posgresql server to listen on arbitrary port
4. rake db:*

## Context
I'm trying to get a closer approximation to production configuration in my development environment, so that I can gain more operational understanding of this app and automate more of the deployment process with confidence that we won't fall over or get hacked.

## Your Environment
CentOS 7
PostgreSQL 9.6

**Comment by Mr0grog** [comment]
OK, we have a variety of different takes on solving DB config better in #294, #359, and #363.

It feels like there are a few different understandings and needs going on here; I’ve tried to pull them all together in #363, but need feedback to know if that’s clear and solves everyone’s different views here.

**Comment by Mr0grog** [comment]
I’m considering the issues here resolved by #363.
