### ISSUE TITLE
Non-Versionista imports need equivalent source & text diff hashes

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#404]
We’ve long planned to add [automated analysis for versions](https://github.com/edgi-govdata-archiving/web-monitoring/issues/62) whenever they get imported, but I had failed to mentally connect the fact that not having done this means our Wayback imports don’t have source & text diff hashes to the fact that analysts heavily rely on those for managing their work. I think this means having some equivalent information for Wayback imports is a high priority for making our Wayback data workable.

There are a few possible solutions here:

1. Do option (2) from edgi-govdata-archiving/web-monitoring#62, which is the right long-term solution here.
    - 👍 It’s generally the right future architecture we’ve agreed on
    - 👎 It requires invention of a whole infrastructure around queuing. We can’t use the same job queue we are using in Rails because it’s not compatible with our Python code. We can’t *just* use SQS because we are committed to a) making the platform workable locally, offline, and b) being minimally dependent on vendor-specific solutions, so we’d need an abstraction layer than can use SQS or something else local.
    - 👎 It requires coordinated changes across 3 projects: DB has to put things on the queue; Processing has to add queue reading and an analysis module; Scraper has to learn to load annotations for every version and use those in its weekly sheets output.

2. Rig up a new job type in DB that loads the appropriate diffs from the diffing server, hashes them, and adds them to either the `source_metadata` (a small lie on the DB’s part to ease compatibility) or makes an annotation with them (requires extra work on scraper’s part).
    - 👍 it’s quick and expedient
    - 👍 it relies on existing infrastructure on only requires changing 1 (or maybe 2) projects
    - 👍 the diffs themselves get pre-cached because DB loaded them! 😀
    - 👎 it adds a whole new body of logic in Ruby when we are trying to switch to Python (#119) and puts that logic in the DB instead of processing (although there’s probably still some debate or discussion worth having there).
    - 👎 It’s an interim solution that is definitely not the right one, and it’s easy for that to get conceptually wedged into place and become a roadblock for getting the right solution.

3. Add an analysis endpoint to the diffing server (or a new, separate server) in the processing project that receives a POST of the DB records for two versions + page (or maybe three versions: a, b, base) and is responsible for POSTing the resulting annotation back to the DB. We’d add a new job type in DB that sends that initial POST to the analysis endpoint.
    - 👍 Does not require any new queuing infrastructure as in option (1) (we’re leaning on DB to manage queuing)
    - 👍 Keeps the analysis logic in Python
    - 👍 This is *really* similar to the ideal solution and has smoother (or at least clearer in *my* head) transition path to the ideal.
    - 👎 On the flip side of that, it feels like the most kludgy setup of all the options, with its feet half in one approach and half in the other 😛
    - 👎 We probably need to make a *second,* separate server in processing or somehow make the diffing server pluggable so that Wayback folks don’t wind up with the added weight of this.
    - 👎 It requires changes across 3 projects again.

Personally, I feel like we don’t really have the time right now for option (1), please speak up if you think otherwise. Of the remaining, option (2) feels fastest and easiest to accomplish, while (3) feels like it gives us a clearer path to (1) after it’s done, even if it’s super kludgy.

@danielballan @jsnshrmn thoughts?

---

P.S. Analyzing every change makes the issues in edgi-govdata-archiving/web-monitoring-processing#154 really important to fix — *especially* the “single giant request failure mode” @danielballan mentioned here: https://github.com/edgi-govdata-archiving/web-monitoring-processing/issues/154#issuecomment-411856360

P.P.S. One performance thing we could also do here is only pre-analyze the latest version of every page in an import. That is, if an import includes two versions (v2 & v3) of a given page, we skip the (v1 → v2) change only analyze the (v2 → v3) change, since v2 is unlikely to ever show up on an analyst sheet.

**Comment by Mr0grog** [comment]
P.P.P.S. I mentioned how 2 (or maybe all, depending) of these options require changes to scraper (because it would have to read changes and annotations, not just versions, when generating sheets), but we could also add some funky logic to DB’s `POST /changes/{id}/annotations` endpoint that stuffs some special annotation fields into the `Version.source_metadata` field. (In this case, `source_diff_hash` and `text_diff_hash` or something like those names.)

**Comment by Mr0grog** [comment]
Ooh, or, relative to the above, we could add two fields to `GET /versions/{id}`:
- `change_from_previous: { [change object] }` and
- `change_from_earliest: { [change object] }`

Scraper would still require code changes, but they’d be very small. Instead of having to request whole new resources, it would just look at those two fields if the info isn’t in the `source_metadata` like it is with Versionista.

**Comment by danielballan** [comment]
I am on board with (2) and the two new fields for `GET /versions/{id}`.
