### ISSUE TITLE
Increase priority for special terms in automated analysis

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#416]
The analyst team has a list of words/terms they consider important, so if we see those terms in textual change, we should bump up the priority.

This list should *probably* be provided by an environment variable, but that might get kinda big. Not 100% sure on the best way to handle this. Maybe a special DB table? (@danielballan @jsnshrmn ?)

The current list is:

### Terms

- adaptation
- Agency Mission
- air quality
- anthropogenic
- benefits
- Brownfield
- clean energy
- Climate
- Climate
- Compliance
- Cost-effective
- Costs
- Deregulatory
- droughts
- economic certainty
- economic impacts
- economics
- Efficiency 
- Emissions
- endangered species
- energy independence
- Enforcement
- environmental justice
- federal customer
- fossil fuels
- Fracking
- global warming
- glyphosate
- greenhouse gases
- horizontal drilling
- hydraulic fracturing
- Impacts
- Innovation
- Jobs
- Mercury
- Methane
- pesticides
- pollution
- Precautionary
- regulatory certainty
- Resilience
- Risk
- Safe
- Safety
- sensible regulations
- storms
- sustainability
- Toxic
- transparency
- Unconventional gas
- unconventional oil
- Water quality
- wildfires

### Co-occurrence:

- State and certainty
- State and deregulatory
- Climate change and resilience
- Clean energy and energy independence
- Benefits and certainty
- Safety and X (statistical relationships)
- Deregulatory and compliance
- Unconventional oil and X (emissions, etc.)
- X and Y (statistical relationships)

**Comment by jsnshrmn** [comment]
first thought off the top of my head: stick this into a postgres json document

**Comment by Mr0grog** [comment]
Could do! Another thought I had: env var that is a URL to the data (e.g. in S3 or something).
