### ISSUE TITLE
Make paging page size customizable

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#44]
Right now you can ask for a given page of results (with the `?page={number}` querystring arg), but you can’t alter how many items are on that page. We might also want to move away from “page” terminology, too, since that can be confusing with the actual web pages we are tracking.

**Comment by danielballan** [comment]
For naming, maybe "chunk" since the response in chunked?

Despite having suggested customizable page size myself, I think this is low priority. We can wait until we have a reason to need it.

**Comment by Mr0grog** [comment]
Just dropping terminology from other systems here:

- `page`, `page_size`
- `chunk`, `chunk_size`/`chunk_length`
- `offset`, `limit` (SQL)
- `skip`, `limit` (Azure, Mongo)
- `from`, `size` (Elastic Search)
- `itemIndex`, `numberofitems` (OpenSearch)
- `cursor`, `size` (sometimes `cursor` is treated as an index, sometimes an ID to continue from, sometimes a totally opaque string that identifies some key in cached data somewhere—the latter two approaches are complex and work differently than our existing paging, but have benefits, like never accidentally having overlapping pages because of inserts)
- `current_page_index`, `page_size` (ASP.Net PagedDataSource)
- `item_page` (Amazon Products)
- `start_after`, `continuation_token` (AWS, see `cursor` notes above)
- `page_token`, `max_results` (Google Cloud, see `cursor` notes above)

**Comment by danielballan** [comment]
:+1: for this comprehensive and well-referenced list! I went with chunk/chunk_size, but I have no strong option here and I'm perfectly happy to change it.
