### ISSUE TITLE
Add `status` field to versions

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#450]
We’ve resisted adding a canonical `status` field to version records before because not all our sources provide that data (Versionista only provides that info for errors, not for successes). However, we need to provide better information about whether pages have been removed (edgi-govdata-archiving/web-monitoring#122) and, to do that well, I think we need to elevate `status` to an official field on versions in order to make calculating it for pages sane.

For existing data, we have:
- `source_metadata.status_code` for `internet_archive` sources
- `source_metadata.error_code` (only present when status >= 400) for `versionista` sources

For future data, we should support `status` in an import record.

The biggest question here is: **what do we do for sources missing this info?** We can either make the field nullable or we can assume `200` if we don’t have status info. (I think in most cases, we’d still assume null values represented `200` if we supported them.)

What needs to actually happen here:

- [x] Add `status` field (an int) to `Version` objects.
- [x] Add a data migration to fill it in for existing records.
- [x] Set the field when importing.
- [x] Make the field queryable?

**Comment by danielballan** [comment]
I think it makes sense to make the fields nullable. Then we'll have a way of telling, "This Version had no explicit status," and we can go on assuming that the status was `200` from there.
