### ISSUE TITLE
Add `status` field to Pages

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#451]
We need to add a `status` field to page objects that attempts to represent what the overall status is for a page right now (we need this on a page level instead of just checking the latest version to account for things like intermittent errors). See edgi-govdata-archiving/web-monitoring#122.

Its value should be calculated on a moving time window. We think the right time window is 14 days, but this should be changeable (either a constant we can modify or a config variable we read in from the environment).

To calculate it, load all the versions of a page over the time window and:

1. If the status code is *successful* (i.e. < 400) more than X% of the time, mark the page’s `status` as `200`. (X should be configurable, but we think it’ll be somewhere between 50-80%.)

2. Otherwise, set the page’s `status` to the most common error status code (i.e. >= 400).

What needs to happen:

- [x] Add an int `status` field to the page record.
- [x] Add a method of updating it (this could be a job that we run regularly or it could be part of the import job). The actual calculation should probably be a method on the `Page` model. (See #619)
- [x] Maybe make this field queryable in the API?

This depends on #450.

**Comment by danielballan** [comment]
I endorse!

**Comment by Mr0grog** [comment]
This work is halfway done. I definitely don’t want to leave it in that state.

**Comment by Mr0grog** [comment]
The final work on scheduling automatic updates is done in edgi-govdata-archiving/web-monitoring-ops#29.
