### ISSUE TITLE
Swagger form on home page doesn't let me create annotations with blank from_version

### ISSUE THREAD

**Issue by jsnshrmn** [edgi-govdata-archiving/web-monitoring-db#456]
I'm not sure if this is a swagger bug, the documentation, or the api itself, but I wanted to make note of it.
I suspect that swagger may be putting some literal strings in place of what should be null/empty values.

## Expected Behavior
I'd expect to be able to leave optional fields empty in the swagger forms.

## Current Behavior
If I leave `from_version` empty in the swagger form, I get 4xx responses back. Note that this field has the following legend
> ID of the “before” Version. If omitted, it will be treated as the version immediately prior to to_version.
and isn't marked as required.

## Steps to Reproduce (for bugs)
leaving from version blank, leads to a request like this:
```
curl -X POST "http://192.168.0.96:30000/api/v0/pages/69fe505d-cc39-4c16-a8a5-1abb2ae05974/changes/undefined..7cf48096-2237-454b-b46e-628019c10451/annotations" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{  \"int\": 100,}"
```

or

```
curl -X POST "http://192.168.0.96:30000/api/v0/pages/69fe505d-cc39-4c16-a8a5-1abb2ae05974/changes/{from_version}..7cf48096-2237-454b-b46e-628019c10451/annotations" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{  \"int\": 100,}"
```

and gets me varying 4xx responses

filling it in shows a request like this:
```
curl -X POST "http://192.168.0.96:30000/api/v0/pages/69fe505d-cc39-4c16-a8a5-1abb2ae05974/changes/b742ecdc-768e-4286-9d34-30d4bebdb848..7cf48096-2237-454b-b46e-628019c10451/annotations" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{  \"int\": 100}"
```
and succeeds
```
{
  "links": {
    "version": "http://192.168.0.96:30000/api/v0/pages/69fe505d-cc39-4c16-a8a5-1abb2ae05974/versions/7cf48096-2237-454b-b46e-628019c10451",
    "from_version": "http://192.168.0.96:30000/api/v0/pages/69fe505d-cc39-4c16-a8a5-1abb2ae05974/versions/b742ecdc-768e-4286-9d34-30d4bebdb848"
  },
  "data": {
    "uuid": "a1fd41c8-4ff8-4038-bc2c-35d3b8e51dc2",
    "annotation": {
      "int": 100
    },
    "created_at": "2018-12-05T21:54:56.050Z",
    "updated_at": "2018-12-05T21:54:56.050Z",
    "author": {
      "id": 1,
      "email": "seed-admin@example.com"
    },
    "from_version": "b742ecdc-768e-4286-9d34-30d4bebdb848",
    "to_version": "7cf48096-2237-454b-b46e-628019c10451"
  }
}
```

## Context
I was using swagger to try to validate a bug fix just using the tooling that was already here.

**Comment by Mr0grog** [comment]
Yeah, this is partially a Swagger bug and partially the fact that having `{thing}..{other_thing}` in the path is invalid (at least in Swagger v2, and we haven't updated to v3, a.k.a OpenAPI).

Some folks have suggested that we change that to `{change_id}` and then set out in the description that `{change_id} = '{from_id}..{to_id}'`. ¯\\\_(ツ)\_/¯

**Comment by Mr0grog** [comment]
See also #65.
