### ISSUE TITLE
Set up error tracking service

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#47]
New Relic may be a good basic approach, but we should probably have some specific error monitoring. Some options:

- Sentry (https://sentry.io) I am a fan, but lament the name confusion it will inevitably have with the [archives project](https://github.com/archivers-space/sentry)
- Airbrake (https://airbrake.io) It does its job, but I have spent a great deal of time butting heads with its UI in the past; I prefer Sentry
- Rollbar (https://rollbar.com) I've seen this advertised all over the place, but have never used it.
- ?

**Comment by Mr0grog** [comment]
Would love any feedback or experience from others.

**Comment by danielballan** [comment]
Unfortunately I have no experience beyond basic uptime monitoring. If you are a fan of sentry, I think we can cope with the name ambiguity. (And the name of the archivers service might still be eligible for reconsideration.)
