### ISSUE TITLE
Automatically tag pages based on domain

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#470]
After talking organizational tools with the analyst team, we think we should automatically tag pages based on their URL — specifically, we want a tag for the full domain/hostname and a tag for the primary domain. There are two places I can think of for this:

- A callback on the Page model when it is first saved.
- Directly in the import job.

And then the remaining question is what the actual tags should be. I think we should use the same `{type of tag}: {tag name/value}` system we do for Versionista sites here, but what should be the “type” for our two tags?

1. `host` and `domain`, e.g:
    - `host: ntwc.arh.noaa.gov`
    - `domain: noaa.gov`

2. `domain` and `primary-domain`, e.g:
    - `domain: ntwc.arh.noaa.gov`
    - `primary-domain: noaa.gov`

3. Something else???

4. Add fields to `Page` instead of tags. We still need to name the fields, though (see above options).

/cc @danielballan @jsnshrmn

**Comment by danielballan** [comment]
Is terminology like [Second-level domain[(https://en.wikipedia.org/wiki/Second-level_domain) useful here?

**Comment by Mr0grog** [comment]
I was trying to think of how to abbreviate it, since it seems a little long. Are you thinking:

- `domain: ntwc.arh.noaa.gov`
- `second-level-domain: noaa.gov`

Or:

- `fqdn: ntwc.arh.noaa.gov` (technically not correct since no dot at the end, but ¯\\\_(ツ)\_/¯)
- `2ld: noaa.gov`

Or something else?
