### ISSUE TITLE
Look into e-mail service providers

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#50]
E-mail is currently sent through a GMail account, which was simple and expedient at first, but really very error prone, as its security mechanisms are designed for human users interacting with a UI. We should really be interfacing (still via SMTP) with a service like:

- Postmark (https://postmarkapp.com)
- Mailgun (https://www.mailgun.com)
- Sendgrid (https://sendgrid.com)
- Mandrill (add-on to Mailchimp)
- Amazon SES (https://aws.amazon.com/ses/)
- Sendinblue (https://www.sendinblue.com)
- ?

**Comment by Mr0grog** [comment]
I have experience with Mandrill before it got integrated into Mailchimp and it was OK. Have heard some good things from others about Postmark, so I would probably lean that way.

**Comment by Mr0grog** [comment]
Archivers is also using Postmark.

**Comment by shapironick** [comment]
This is helpful. What do you think the email volume of this would be over say a year? So I can think about $$. 

Sent on the move

**Comment by Mr0grog** [comment]
[Versionista Scraper](https://github.com/edgi-govdata-archiving/web-monitoring-versionista-scraper) sends roughly 22/month (2 e-mails every three days). This project sends e-mails for:

- Sign-up Invitations (optional)
- Sign-up Confirmations
- Password reminders

Right now we have < 20 analysts, so that's a one-time cost of 40 e-mails and then, say, 20/month if everyone forgets their password once. Then it's just about supporting a much wider/broader group of people to do analysis.

So for now: ~45/month
For future: ??? but probably not a lot.

**Comment by Mr0grog** [comment]
Basically our needs are absurdly small at the moment ;)

**Comment by Mr0grog** [comment]
That said, we don’t have a strong need to for extra analytics or reporting, so I think it’s reasonable to view these services as a commodity if pricing is a concern.

**Comment by Mr0grog** [comment]
@shapironick Also, does EDGI have organizational e-mail at `envirodatagov.org` (or somewhere else)? If so, we should really have these applications sending from e-mail addresses at that domain.

**Comment by dcwalk** [comment]
Just to update on this on issue (from convo in `#tools_talk` on EDGI slack):

- EDGI currently doesn't have existing organizational email at `envirodatagov.org`. 
- We've consolidated DNS and hosting and set up team access for editing DNS records

Still need to confirm *by May 26* whether there is an existing domain purchased by @titaniumbones we want to be using for email or whether we are okay to go ahead with `envirodatagov.org`
