### ISSUE TITLE
Collect metrics in Elastic.

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-db#505]
## Goal

Collect structured data from Rails app, starting with regular updates on queue size and updates when things are submitted and processed.

## Short-Term Plan

Use [httparty](https://github.com/jnunemaker/httparty) to submit some requests to elasticsearch at various points in the import worker's process.

## Medium-Term Plan

Unify this with the logging framework.

1. Use https://rocketjob.github.io/semantic_logger which claims to be a drop-in replacement for the default logger that accepts normal log messages (strings) or objects.
2. Make sure all the existing logs still work.
3. Stand up Elastic's Curator which culls indexes based on some policy (i.e. keep the last month...)
4. Use semanatic_logger's elastic plugin to send all logs to our elastic cluster.
5. Add some new _structured_ log messages related to the queue.
6. Visualize their output in Kibana.

Thoughts?

**Comment by Mr0grog** [comment]
Short term plan sounds good to me.

Medium term plan:

- Is it possible there’s a better way to integrate this with the [fluentd setup](https://github.com/edgi-govdata-archiving/web-monitoring-ops/tree/master/templates/kube-system/fluentd) we already have?

- I gather Kibana is more about aggregated stats; can we view raw logs/messages over a given time period, or do we need to be careful to split the log stream so logs to to both Elastic and our existing Cloudwatch buckets? (Seeing long messages around an error is still occasionally really useful in understanding a complex error in production.)

**Comment by danielballan** [comment]
I don't immediately know the answer to either question, but I agree that both should be answered before we start writing code.
