### ISSUE TITLE
Rethink Pagination

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#579]
Last week, I made a bunch of changes to our database’s configuration (edgi-govdata-archiving/web-monitoring-ops#26) and to the indexes for the versions table (#548) to address massive performance issues we were hitting. Those have made a big difference, but we have one remaining major problem: the `count(*)` queries we use for pagination.

Most of our endpoints that return lists (e.g. `/api/v0/versions`) return a json:api inspired structure like:

```js
{
  "links": {
    "first": "https://api.monitoring.envirodatagov.org/api/v0/versions?chunk=1&chunk_size=100",
    "last": "https://api.monitoring.envirodatagov.org/api/v0/versions?chunk=23042&chunk_size=100",
    "prev": null,
    "next": "https://api.monitoring.envirodatagov.org/api/v0/versions?chunk=2&chunk_size=100"
  },
  "meta": {
    "total_results": 2304117
  },
  "data":[...]
}
```

In order to figure out the `last` page, the first thing we always do is run a `count(*)` version of the query that would produce our results (e.g. for `SELECT * FROM versions;`, we’d first do `SELECT count(*) FROM versions;`). That lets us calculate how many chunks/pages of results we have. As a bonus, we added the `meta.total_results` field, which several active use cases (e.g. the [healthcheck script](https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/ce0d2e3d4c712b22196bf10da0a46a82fddf46d1/scripts/ia_healthcheck#L23-L36)) now depend on.

Unfortunately, `count(*)` is pretty slow in Postgres, especially if the whole table does not fit in memory. For example, `GET /api/v0/versions` currently takes a little over 18 seconds: 18 seconds for the count, and 30 *milliseconds* for the actual data. While use cases like the healthcheck require some kind of support for `count`, **we need to take `count` out of the critical path for pagination.**

Some ideas:

1. Do some fancy footwork and cache the `count` results, either in a table or in Redis. Every time we import, we would clear the cache.

2. Postgres 9.5+ has a fancy-pants [sampling system](https://www.postgresql.org/docs/devel/sql-select.html#SQL-FROM) for doing quick estimations: `SELECT 100 * count(*) AS estimated_total FROM versions TABLESAMPLE SYSTEM (1);` We could use estimated counts. (This still gets slower as the table grows, but relatively speaking, it’s quite speedy.)

3. Just remove `links.last` and `meta.total_results` from the data and determine if we are on the last page based on whether there were `< chunk_size` results. For applications that need `total_results`, we could:
    1. Have a query parameter like `?include_total` that runs the `count` query.
    2. Have a new endpoint on all collections like `/api/v0/versions/count` that runs just the count query.

4. Switch to a fundamentally different kind of pagination based on the actual data. (Twitter’s API is one example of this; you ask for a number of results and a key to return results *after*.) This would be a big shift, and comes with some pros and cons:
    - 👍 Super fast! Offset-based pagination like ours gets slower on each subsequent page of results. This can leverage an index to get to the beginning of the results pretty quickly.
    - 👍 You never miss or duplicate results because new data got added while you were iterating through pages of results.
    - 👎 Not very flexible. We currently allow sorting on pretty much any column, and this would require us to limit those options (you have to have a sortable column with unique values☨ for this technique). On the other hand, I’m not sure of any *common* use-cases we have that sort on anything other than `created_at`, `updated_at`, or `capture_time`, so this might not be too bad.
    - 👎 It’s harder to randomly skip around because the key you resume from is probably unpredictable. (See the health-check use case.)

    @bensheldon suggested the [`order_query` gem](https://github.com/glebm/order_query) for this on [Twitter](https://twitter.com/bensheldon/status/1162441235061080064). This site also has lots of info on the general technique: https://use-the-index-luke.com/no-offset

I don’t think (1) and (2) are good solutions. (1) only works well for tables that don’t update often (e.g. good for versions, so long as we keep doing big batch imports, but bad for annotations and changes) and is a lot of extra hacky stuff to add. (2) will still slow as the table grows, and means we could possibly suggest there are more or fewer pages than there actually are.

(3) Feels like a good short term solution. I prefer (3.2) to (3.1) even though it’s more work, but don’t have a strong preference.

(4) Feels like the *right* solution to me, but I’m also OK putting it off a little bit. It’s not immediately obvious to me how to efficiently do random sampling for the health-check use case with it. (Maybe just pick a bunch of random dates to query by?) On the other hand, putting it off is a recipe for never doing it.

cc @danielballan

---

☨ In Postgres, you can use a multicolumn key, like `uuid + created_at` to get sortable uniqueness, so we don’t need to invent new columns here. :)

**Comment by Mr0grog** [comment]
One other note here: this is mainly a problem for the `/api/v0/versions` endpoint and, to a *much lesser* extent, the `/api/v0/pages` endpoint. I think it’s important to take a universal approach across all endpoints, though.

**Comment by Mr0grog** [comment]
This will affect the healthcheck script, the python API wrapper, our analyst sheet generation tools, the UI project, and any other tools people like @ericnost have developed.

**Comment by SYU15** [comment]
So for solution `3.2`, is the implication that we'd need to make a new API call to get the total number of pages to generate the pagination? Why is `3.1` preferable? Mainly because the API design will be cleaner? I have a slight preference for minimizing the number of calls made from the UI but if one approach is significantly faster/better, it's not that big of a deal.

**Comment by Mr0grog** [comment]
> I have a slight preference for minimizing the number of calls made from the UI but if one approach is significantly faster/better, it's not that big of a deal.

Ah! So I think the bigger thing here is that in any version of (3) or (4), you should *avoid ever asking for the number of pages/chunks*. You wouldn’t get it by default, and the intended case is that that you just keep iterating to the next chunk, and the next chunk, until you hit the end (because it takes milliseconds to look up a single chunk, but many seconds, during which the app and database are both somewhat tied up, to count how many chunks there are). It’s mainly an option for narrow cases where you *really* need to know or for backwards compatibility.

> So for solution 3.2, is the implication that we'd need to make a new API call to get the total number of pages to generate the pagination?

Yep.

> Why is 3.1 preferable? Mainly because the API design will be cleaner? I have a slight preference for minimizing the number of calls…

Yeah, I was partially thinking (3.2) would be preferable because it feels cleaner, but also because forcing you to make a separate call makes you think a lot harder before doing the really expensive, costly thing.

That said, it’s a good point that adding `?include_total` to a normal call would let you do two things at once and be at least slightly more efficient. I guess I wasn’t really thinking about that.

**Comment by Mr0grog** [comment]
OK, I think the first step here is going to be implementing (3.1). Then we can come back and evaluate whether and when to do (4).

- [ ] Update healthcheck script to use `?include_total`.
- [ ] Update weekly analyst task sheet script to not check totals or last page link.
- [ ] Update DB to only show `meta.total_records` and `links.last` when `?include_total` is set.

**Comment by danielballan** [comment]
> Yeah, I was partially thinking (3.2) would be preferable because it feels cleaner, but also because forcing you to make a separate call makes you think a lot harder before doing the really expensive, costly thing.

Weighing in a bit late... For what it's worth, I like 3.2 a little better than 3.1 for this reason, but the argument for 3.1 is fair and, as you say, easier to implement.

**Comment by Mr0grog** [comment]
Coming back to this *way* later:
- Yes it works in reverse, though you have to be careful to specify the order on both parts of the compound key (e.g. `created_at: :desc, uuid: :desc`).
- For versions, we also commonly scope queries by page. The indexes described above don’t help with that (instead, PG combines the existing indexes on `created_at` and on `page_uuid`), but if there’s another index with `page_uuid` *first* (not last), it will get used and make things pretty speedy. Scoping by page already slims down the data set enough that things are reasonably fast, so this may not be worthwhile. Or maybe it’s useful to *replace* the index on `page_uuid`.

**Comment by Mr0grog** [comment]
This is done for versions, and I’m marking it as complete. That said, it is not in place for any other controllers/models. I don’t currently plan to implement it anywhere else right now, since other parts of the app are not in major need of it.
