### ISSUE TITLE
Switch MAINTAINER to LABEL directive in Docker

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#583]
We use the `MAINTAINER` directive in our docker files, but it’s been deprecated:

> The `LABEL` instruction is a much more flexible version of this and you should use it instead, as it enables setting any metadata you require, and can be viewed easily, for example with docker inspect. To set a label corresponding to the `MAINTAINER` field you could use:
> 
> ```
> LABEL maintainer="SvenDowideit@home.org.au"
> ```

- [`MAINTAINER` docs](https://docs.docker.com/engine/reference/builder/#maintainer-deprecated)
- [`LABEL` docs](https://docs.docker.com/engine/reference/builder/#label)

**Comment by amoury** [comment]
Hi @Mr0grog , is anyone working on this issue? If not, I'd like to take this

**Comment by Mr0grog** [comment]
Nope, go ahead! :)

**Comment by amoury** [comment]
@Mr0grog thank you for assigning this to me. I have opened the PR for the same https://github.com/edgi-govdata-archiving/web-monitoring-db/pull/613
