### ISSUE TITLE
Track titles on Version instead of Page

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#59]
See #57 for the original discussion on this.

Since page titles can change over time (and are really just part of a page’s content), we should add a `title` field to the Version model and make Page’s `title` merely a reflection of the latest Version’s title.

This can probably be best handled in the [`after_save` callback](http://guides.rubyonrails.org/active_record_callbacks.html#updating-an-object) on Version or the [`after_add` callback](http://guides.rubyonrails.org/association_basics.html#association-callbacks) on Page’s association with versions. We should also keep in mind that the Page’s title should always reflect the version with the latest `capture_time`, not necessarily the last one added to the database (they can be added out of order).

**Comment by maxtedford** [comment]
@Mr0grog, are still looking for some help with this? If so, I'm happy to take a stab at it.

**Comment by Mr0grog** [comment]
Yes! If you are interested in working on this, that would be wonderful, thank you.

**Comment by Mr0grog** [comment]
@maxtedford If you’re working on this, let me know. You should also feel free to hop on our Slack chat: https://archivers.slack.com/ (in the #webmonitoring channel).

**Comment by maxtedford** [comment]
Hey @Mr0grog, I haven't started on it yet, but I plan to in the coming days. I'll jump on your Slack channel too in case any questions come up. Great suggestion!

**Comment by maxtedford** [comment]
It actually looks like I can't join the Slack org without an invitation. Possible to send one my way?

**Comment by Mr0grog** [comment]
Oh, sorry! https://archivers-slack.herokuapp.com/
