### ISSUE TITLE
Automatically tag news/blog pages with `news` tag

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#594]
A while back, we manually tagged all pages with `news` or `blog` in the URL’s path using the `news` tag. We should probably just build this feature in for imports, the same way we automatically tag `domain:<domain>` and `2l-domain:<second-level domain>`.

You can see where we currently do this in the `Page` model: https://github.com/edgi-govdata-archiving/web-monitoring-db/blob/42bb8c7020e4d139fa278a95e0947cf9c8329659/app/models/page.rb#L122-L125

Tag a page as `news` if:

- The URL path contains `news`
- The URL path contains `blog`
- The URL path contains `press`
- ?

**Comment by ewelinasobora** [comment]
I'd like to work on this issue :)

**Comment by Mr0grog** [comment]
@ewelinasobora great! Let me know if you have any questions, or post a draft PR if you need any help or feedback before it’s entirely ready.

**Comment by ewelinasobora** [comment]
@Mr0grog Thanks! Feedback will be helpful for sure :)
