### ISSUE TITLE
uuid stability of pages/versions ingested from Versionista

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-db#62]
Can I count on the uuids of the Pages and Versions ingested from Versionista beings stable at this point? And are they the same between the staging and production deployments, or independently generated?

(Apologies for the cross-post, Rob -- I asked this in Slack and then realized the answer might be useful to others too.)

**Comment by Mr0grog** [comment]
On production (https://web-monitoring-db.herokuapp.com): **Yes**

On staging (https://web-monitoring-db-staging.herokuapp.com): **Sort of.** Data on staging might be blown away and rebuilt at any given point, but hopefully we won't need to do that often. (This has only happened once so far.)
