### ISSUE TITLE
Add “effective time” querying for versions?

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#632]
We can currently query versions based on their `capture_time`, which is obviously a fairly critical feature. However, there are a lot of cases where it would be nice to query by a version’s “effective time,” or the date range during which it represented the current status of a page.

This is especially useful for answering questions like “what did a page look like before and after X time range?” (We do this when generating analyst sheets, for example.)

Would this be worthwhile to add? What would we name the query parameters?

To make this feasible without killing the database, we’d probably have to a field to Version records that represents the end of its effective time. That’s not so great because it’s denormalized data and we have to be careful to keep it up to date (like we do with `different`).

It’s possible adding an index on `(page_uuid, capture_time)` might allow us to do it with a UNION query, but that needs some testing to see what it costs Postgres:

```sql
(
  SELECT * FROM versions
    WHERE capture_time >= '{start date}'
    AND capture_time < '{end date}'
)
  UNION
(
  SELECT DISTINCT ON (page_uuid) * FROM versions
    WHERE capture_time < '{start date}'
    ORDER BY page_uuid, capture_time DESC
)
```

We could also only allow it when the Page ID is also specified, e.g. on `/pages/{id}/versions` but not on `/versions`. That would let us use a UNION like the above, but only in situations where we can be confident it’s fast.

**Comment by Mr0grog** [comment]
Worth noting that “effective time” isn’t a real thing — it’s just a useful construct for some analyses — and there’s some concern an API for this would suggest a false reality. (i.e. We can’t know that a page actually stayed looking the same across any timeframe, we only know that we looked at certain points in time.)

**Comment by Mr0grog** [comment]
Another API approach might be pairing a boolean like `include_previous` with `capture_time`, which would avoid the “false reality” concern above. (It still comes with all the same implementation issues, though.)

**Comment by bensheldon** [comment]
another option. I think this could be done with a lateral join like:

```sql
SELECT * 
FROM versions v0
LEFT JOIN LATERAL (
  SELECT capture_time AS active_until_time
  FROM versions
  WHERE 
    page_uuid = v0.page_uuid AND
    capture_time > v0.capture_time
   ORDER BY capture_time ASC
   LIMIT 1
) ON true
WHERE page_uuid = ? AND 

```

**Comment by Mr0grog** [comment]
Quick indexing notes:
- We have an index on `capture_time`
- If we add an index on `(page_uuid, capture_time)`, it can be used in capture_time-only queries, but it’s not great (i.e. we could drop the index on `capture_time`, but some queries would slow a lot).
- If we add an index on `(capture_time, page_uuid)`, it can be used in this and capture_time-only queries. Both are a little slower than having both a `(capture_time)` and a `(page_uuid, capture_time)` index. This would let us feasibly have one index instead of two, but it all queries do experience some slowdown (~50% speed cost).

**Comment by Mr0grog** [comment]
With the proper index (see above), the lateral join performs *way* better than the union when querying across many pages.

So assuming this is an important use-case, I think the cost trade-offs to evaluate here is:

- The lateral join approach needs…
    - More complex query code
    - An extra index.
    - Is slower (tens of milliseconds).
- The denormalized `effective_end_time` (or whatever we name it) field needs…
    - More book-keeping at import-time, similar to how we handle `different`.
    - An extra index
    - Is faster (not tested, but would expect similarity to `capture_time` queries, which are sub-millisecond).

**Comment by danielballan** [comment]
Given that we have accepted that _one_ denormalized thing (`different`) is OK and useful, I think adding a second one (`effective_end_time` or whatever we name it) is reasonable.
