### ISSUE TITLE
Add banner to top of home page based deployment environment

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#67]
It’d be helpful to display some sort of banner on the top of pages on the test/staging site (and maybe in dev, too?) to remind someone that they aren’t looking at the production instance of the app.

For the API, we could potentially include a special key in the JSON object or an `x-environment` HTTP header (less obvious, but probably a more wise approach).

**Comment by rdalin82** [comment]
I am new to the project and would like to try my hand at this issue.  Are you looking for something like the below screenshot? 

![webmonitor-env](https://cloud.githubusercontent.com/assets/5727364/26757487/648ef496-4882-11e7-9557-3ad5d3e08d6e.png)

**Comment by Mr0grog** [comment]
@rdalin82 I was thinking:

- Above existing header, so it might be easier to share the same design with `web-monitoring-ui` (https://github.com/edgi-govdata-archiving/web-monitoring-ui/issues/67), and
- Maybe more colorful so it is somewhat eye-catching?

Otherwise, yeah! It would be lovely if you wanted to work on this :)

**Comment by Mr0grog** [comment]
Fixed in #72.
