### ISSUE TITLE
Remove migrations related to `versionista_*`

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#69]
…or just squash the migration history. There are a few migrations that use models for tables that were removed—their purpose was really to keep production data in the right shape. People keep trying to migrate an empty database from an initial state all the way to current, though, which does not work because of the removed models. (Rails style is to start a new database by loading the current schema rather than migrating from scratch.)

We should just squash/remove the no-longer-functional migrations so people can migrate across all of history.

**Comment by katelovescode** [comment]
I can take this! #hacktoberfest
