### ISSUE TITLE
Remove deprecated non-API pages

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#73]
Once upon a time, in the very first implementation of all this, I had JSON + HTML routes at:

- `/pages`
- `/pages/{page_id}`
- `/pages/{page_id}/versions`
- `/pages/{page_id}/versions/{version_id}`
- `/pages/{page_id}/versions/{version_id}/annotations`

Those have all long-since been superseded by the `/api/v0/*` routes and I’m not aware of any clients using them. We should take them out.

**Comment by Mr0grog** [comment]
Bumping this up in priority since it seems someone (or many people?) are now hitting these old, no longer relevant APIs regularly—and they are *extremely* non-optimized, causing a heavy load.

**Comment by lightandluck** [comment]
Double checked and I'm not using it anywhere.
