### ISSUE TITLE
Postmark could be moved as a production gem

### ISSUE THREAD

**Issue by KrzysztofMadejski** [edgi-govdata-archiving/web-monitoring-db#76]
`gem 'postmark-rails' ` is an external paid service. It would make more sense to put it in the `:production` bundler group. 

It shouldn't be required for development.

**Comment by Mr0grog** [comment]
It’s in development so you can use it there if you want and so it can be tested. The default dev configuration does not use it, so you’re not locked into it by any means.

**Comment by KrzysztofMadejski** [comment]
Ok, that's great, thanks for clarification.

**Comment by Mr0grog** [comment]
Hmmm, the more I think about this, the more I think you were right, @KrzysztofMadejski. I might have needed to run this locally when setting up the account, but that's almost certainly unusual, and anybody who wants to can easily opt-in to installing production dependencies if they want.

Do you want to make this change?

**Comment by KrzysztofMadejski** [comment]
Sure, I will do it.

**Comment by KrzysztofMadejski** [comment]
I've added it also to the `postmark` group, so you can run `bundle install --with postmark` also while developing.
