### ISSUE TITLE
Use standard PASSWORD for admin

### ISSUE THREAD

**Issue by KrzysztofMadejski** [edgi-govdata-archiving/web-monitoring-db#78]
For development it would be easier if admin password was not [random uuid](https://github.com/edgi-govdata-archiving/web-monitoring-db/blob/master/db/seeds.rb#L3), but "PASSWORD", because it's written like this in [default processing's .env file](https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/master/.env.example#L10). 

This way it would work out of the box. 

Random password is ok for setting production env, but then you are not seeding data, right?

**Comment by Mr0grog** [comment]
That seems like a good idea. I was probably being unnecessarily paranoid when I did the random password thing. If you want to fix this, that’d be great.
