### ISSUE TITLE
Adopt setup philosophy of 18f/identity-idp repo

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/web-monitoring-db#83]
Inspired by #79

I was wondering whether folks were interested in taking cues from the login.gov setup scripts. I came across it last year, and for such a complicated system, it was truly a thing of beauty.

Basically, after service setup, just:

```
make setup
make run
```

- Do we even think it's a good idea to hide the setup steps? (i can imagine valid rationale to expose new follks to basic commands)
- Does `make` feel like a good choice of tool? (ie not requiring some lang-specific build tool)
- Do we use advanced postgres features? If not, is it worth entertaining the idea of using sqlite for first-time bootstrap, to remove one more piece that might be a bump? We could always encourage people to use postgres after they've been around for a bit and going deeper, but might be cool to not require it for first contribution? (login.gov codebase relies on advanced postgres features, but maybe we don't use things like jsonb extension, etc.)

**Comment by Mr0grog** [comment]
These concerns were meant to be addressed in #16, which needs updating.

**Comment by Mr0grog** [comment]
> Do we use advanced postgres features?

OH YES.

**Comment by patcon** [comment]
My system is apparently futz'd, and so I haven't been able to get docker working for the past 9 months. I'm at the point where I'll probably just buy a new harddrive and reformat my machine to get it working -- too many years of cruft

Just realized I didn't link the login.gov codebase (which uses both docker and non-docker fwiw):
https://github.com/18F/identity-idp

Anyhow, I'll close this for now, if we'd prefer to just use the docker route. thx for response

**Comment by KrzysztofMadejski** [comment]
It's always a debatable question how much of a setup scripts one should provide. When you are building scripts you have to take into account all the OSes, versions, etc. From my experience it soon becomes too complex for a newbie to go through, and too simple for advanced users. I'm more for Troubleshooting readme section that guides through common problems, added as they arise.

I want to try out soon http://docs.pybossa.com/en/latest/juju_pybossa.html and their approach to install which is basically one click to install Virtual Box + guest OS + environment + app, and then mount locally harddrive + do tunnels to see it locally.
