### ISSUE TITLE
Receiving duplicate records from filter query

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/web-monitoring-db#85]
Querying the `/pages` route using `site` and `capture_time` parameters returns duplicate entries in the response.

## Steps to reproduce
1. [Sample query](https://web-monitoring-db-staging.herokuapp.com/api/v0/pages?site=State%20-%20state.gov&capture_time=2017-06-01..)
2. Compare 2nd and 3rd entries (they begin with UUID="31aba984-7faf-4ace-9c6c-1056b51b9b6a"). They are exactly the same.

## Context
In [staging UI](https://web-monitoring-gapi.herokuapp.com/loggedIn/eric@gmail.com), filtering the list by user, React will throw numerous warning messages:

```Warning: flattenChildren(...): Encountered two children with the same key, `31aba984-7faf-4ace-9c6c-1056b51b9b6a`. Child keys must be unique; when two children share a...```

React will display the first record and toss all duplicates, which isn't a blocking issue, but doesn't seem desirable. Not sure if the duplication is expected behavior from querying the DB in this way.

**Comment by lightandluck** [comment]
Resolved by #86

**Comment by Mr0grog** [comment]
Whoa, don’t close this until we’ve actually merged the fix!

**Comment by lightandluck** [comment]
Whoops, sorry about that! Thought I saw you self-merge this PR because it seemed a minor change. Good to know it automatically closes. Thanks!
