### ISSUE TITLE
Denormalize `Page#latest` and `Page#earliest`

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#858]
The main list view of the UI calls `/api/v0/pages?include_latest=true`, and in the production database, this now takes many *seconds* to complete. Under the hood, the query that gets the latest version of each page in the result set is the culprit: https://github.com/edgi-govdata-archiving/web-monitoring-db/blob/d971f1940d6aa9e346c469c5a1e627ff7e67ff28/app/models/page.rb#L35-L46

This is about as optimized as I can think to make such a query — I’ve experimented with other approaches, CTEs, subqueries, more indexes, etc., but the fundamental problem is that the DB just has to scan too many rows to find the “latest,” no matter what approach we take here.

The UI does this query in order to show when the page last changed. We could resolve the user-facing issue here by removing that column, but it feels like a pretty important piece of data.

Instead, I think it might be time to denormalize some information about the latest version of the page. We could either:
- Add a column with the time of the latest version, e.g. `latest_version_time`, or
- Add a column with the ID of the latest version, and join on it, i.e. `latest_version_uuid`

The former would solve the need to show the capture time in the UI and be the most performant, but the latter would be a more flexible (and compatible) approach, since we’d still be returning a full version object in the `latest` field.

The best place to do this would probably be in `Version#sync_page_title`, where we are updating a denormalized title on the page. It’s pretty much the same condition, we’d just be updating another column: https://github.com/edgi-govdata-archiving/web-monitoring-db/blob/d971f1940d6aa9e346c469c5a1e627ff7e67ff28/app/models/version.rb#L158-L168

**Comment by danielballan** [comment]
* Denormalizing seems reasonable.
* Do both version time and foreign key. Having the version time in their is convenient for sorting, filtering.
* Add an index :upside_down_face:

**Comment by Mr0grog** [comment]
Tested out adding an index on `(page_uuid, capture_time DESC) WHERE different = true`, but it sadly doesn’t make any difference. The new index gets used, but only in the same way an index of just `page_uuid` would get used: it picks all the versions with that `page_uuid`, then scans that heap and sorts. It doesn't seem clever enough to do all that work just using the index. 😞

Whether I do the current `DISTINCT ON (page_uuid)` query or use a `RANK()` function (fancy new thing I learned about a few months back), `EXPLAIN ANALYZE` always starts with this at the core of the plan:

```

**Comment by Mr0grog** [comment]
Tested out adding an index on `(page_uuid, capture_time DESC) WHERE different = true`, but it sadly doesn’t make any difference. The new index gets used, but only in the same way an index of just `page_uuid` would get used: it picks all the versions with that `page_uuid`, then scans that heap and sorts. It doesn't seem clever enough to do all that work just using the index. 😞

Whether I do the current `DISTINCT ON (page_uuid)` query or use a `RANK()` function (fancy new thing I learned about a few months back), `EXPLAIN ANALYZE` always starts with this at the core of the plan:

```
->  Bitmap Heap Scan on versions  (cost=97.34..4449.32 rows=1145 width=1309) (actual time=0.199..0.992 rows=684 loops=1)
        Recheck Cond: ((page_uuid = ANY ('{<LIST_OF_UUIDS>}'::uuid[])) AND different)
        Heap Blocks: exact=515
        ->  Bitmap Index Scan on test_index_page_uuid_capture_time_different  (cost=0.00..97.05 rows=1145 width=0) (actual time=0.146..0.146 rows=684 loops=1)
            Index Cond: (page_uuid = ANY ('{<LIST_OF_UUIDS>}'::uuid[]))
```

**Comment by Mr0grog** [comment]
Well, I had a stroke of very twisted brilliance while looking at the EXPLAIN output. If you only select the fields that are in the index, it figures out how to do all the work in one step directly on the index. So you can combine that with a join to get this very twisted but quite speedy approach:

```sql
SELECT versions.*
FROM versions
  INNER JOIN (
    SELECT
      DISTINCT ON (page_uuid) page_uuid, capture_time
      FROM "versions" WHERE "versions"."different" = true AND "versions"."page_uuid" IN (
        <PAGE_UUID_LIST>
      )
      ORDER BY versions.page_uuid, versions.capture_time DESC
  ) as latest
  ON
    versions.capture_time = latest.capture_time
    AND versions.page_uuid = latest.page_uuid;
```

Now the question is how to do that in ActiveRecord. Denormalizing might still be more straightforward, though.

**Comment by Mr0grog** [comment]
That said, the above does *not* work for `earliest` instead of latest. Switching from `capture_time DESC` to `ASC` deoptimizes and flips it back to not doing all the work on the index.

> Now the question is how to do that in ActiveRecord.

Looks like you can pass a SQL string to `joins`, so this can be something like:

```rb
Version.joins(
  <<-QUERY
    (
      SELECT DISTINCT ON (page_uuid) page_uuid, capture_time
      FROM versions
      WHERE different = true AND page_uuid IN (
        #{page_ids.collect {|id| "'#{id}'"}.join(",")}
      )
      ORDER BY page_uuid, capture_time DESC
    ) as latest
    ON versions.capture_time = latest.capture_time AND versions.page_uuid = latest.page_uuid
  QUERY
)
```
