### ISSUE TITLE
Upgrade to CircleCI 2.0

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-db#99]
CircleCI v2 is out of beta, so we should upgrade when we have time.

https://circleci.com/docs/2.0/migrating-from-1-2/

**Comment by danielballan** [comment]
Yep, and it's _really_ nice to use!

**Comment by frederikspang** [comment]
Doing.

**Comment by danielballan** [comment]
Awesome, thanks!
